### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/userstyles#1]
Thought I should create a general feedback issue so people don't have to open one for each minor concern.

I haven't looked at all the individual userstyle directories yet - but 2 are wrongly categorized as userstyles:
- DuckDuckGo (it's just loading the theme into your cookies at the moment)
- Stable Diffusion Web UI (it is CSS, but it's available as an actual Extension for the host, essentially a Marketplace)

We should update them in the `ports.yml` as agnostic - the goal for DDG at least is that we someday have an actual userstyle...

**Comment by sgoudham** [comment]
Oh lol, yeah I just basically took the ports.yml and generate code and modified it

Agreed with both

**Comment by sgoudham** [comment]
Also I think we really need to use `git lfs`.

My git push is capped at like 500 kibs and it's taking forever to push it all

**Comment by sgoudham** [comment]
Also @nekowinston, I think you would have enjoyed this process :laughing: 

![image](https://user-images.githubusercontent.com/58985301/221390293-f70db40b-ec78-4806-8ca4-8975e4543a91.png)

**Comment by nekowinston** [comment]
Good point, I hadn't thought of that previously. 95MB is pretty concerning if we're going to have multiple people maintaining this.
Pretty funny how the largest Repos are all filled with PNGs, while the WEBP barely contribute to the size.

Since we're essentially starting out from tabula rasa with this repo, we should again consider getting rid of screenshots in individual repos. Neovim, our highest-profile repo aside from the main one, already isn't following our screenshot guidelines...

**Comment by sgoudham** [comment]
> > Also I think we really need to use git lfs.
> > My git push is capped at like 500 kibs and it's taking forever to push it all
> 
> Good point, I hadn't thought of that previously. 95MB is pretty concerning if we're going to have multiple people maintaining this. Pretty funny how the largest Repos are all filled with PNGs, while the WEBP barely contribute to the size.
> 
> Since we're essentially starting out from tabula rasa with this repo, we should again consider getting rid of screenshots in individual repos. Neovim, our highest-profile repo aside from the main one, already isn't following our screenshot guidelines...

Well I don't think it's bad when they're individual repositories right, it's just when it's all combined... we have this. I personally quite like the screenshots but yeah I get both sides of this. 

Is there a nice middle ground?

It's just taken me **10 minutes** to force push everything, we definitely can't keep it this way that's for sure
![image](https://user-images.githubusercontent.com/58985301/221390448-189168fb-90b0-4a81-b212-f13ef4f85918.png)

**Comment by sgoudham** [comment]
Woops, the actions workflow has committed `deno_cache`, probably should have saw that one coming

**Comment by nekowinston** [comment]
> Is there a nice middle ground?

Yeah, I've been working on something toolbox/catwalk related, I think we could also solve the screenshot storage problem with that. I'm weary of just chucking stuff onto the GitHub CDN for screenshots - I think it's alright in edge cases, but I would hate for us to depend on GitHub for everything.

The idea is to have a web interface for catwalk, to remove the install step. When combined with a GitHub login & S3 storage, we could self-host it.

> Woops, the actions workflow has committed `deno_cache`, probably should have saw that one coming

What we don't put up with for those fast workflows...

**Comment by sgoudham** [comment]
Time to remove everything from GitHub and chuck to it big Jeff :sunglasses: 

(All seriousness, sounds good for stopping our reliance on GitHub's CDN. I wasn't feeling that great even when I was referencing GitHub links in the generate code from here to `catppuccin/catppuccin/resources/generate` lol)

**Comment by sgoudham** [comment]
In the short term, there are probably 3 immediate solutions

1. Remove individual Latte, Frappe, Macchiato, and Mocha screenshots and just keep the catwalk screenshot? 
2. Use Git LFS (I don't know how impactful this is) + ImgBot image compression? 
3. Remove all the screenshots entirely?

**Comment by nekowinston** [comment]
Just by running
```sh
find . -name "*.png" -exec convert -quality 95 {} {}.webp \;
```

I'm able to reduce the size of all *current* assets to 27MB:
```sh
$ find . -name "*.webp" -print0 | du --files0-from=- -hc | tail -n1
> 27M     total
```

**Comment by sgoudham** [comment]
How could I forget the 4th solution: 

4. winston's brain

**Comment by nekowinston** [comment]
I've managed to cut it down to 16MB.
Quick note: youtubemusic seems to store some PNG files which it uses in its stylesheet. So I'm not converting those to webp:
```sh
# convert & delete PNG files
find . -name "*.png" -exec sh -c 'convert "$1" "${1%.png}.webp"' _ {} \; -exec rm {} \;
# reset youtubemusic
git restore styles/youtubemusic/assets/icons/ && rm styles/youtubemusic/assets/icons/*.webp
```

```sh
$ find . -name "*.webp" -print0 | du --files0-from=- -hc | tail -n1
> 16M     total
```

We should re-initialize the repository at some point though, since my `.git` folder now north of 160MB.

**Comment by sgoudham** [comment]
Yeah it'd be great if you want to do that since you have the images locally and I wouldn't want to take any credit :heart: 

Lovely work!

**Comment by nekowinston** [comment]
I have committed all converted WEBP images, and I think I also rewrote most of them to use relative URLs, e.g. `assets/preview.webp` instead of `https://raw.githubusercontent.com/**/*.png`.

**Comment by rubyowo** [comment]
The DDG userstyle is almost done. I just need to add some finishing touches.
