### ISSUE TITLE
Various areas of chess.com unthemed

### ISSUE THREAD

**Issue by kocosmanberke** [catppuccin/userstyles#1029]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:chess.com

### Describe your problem.

I installed Stylus extension for Firefox and then clicked **Stylus Install** button on chess.com catppuccin page. Button redirected me to some css file and i enabled it, but it doesn't work. 

### What browser(s) are you seeing the problem on?

Firefox 127.0.2

**Comment by uncenter** [comment]
Are you sure you clicked install when it opened the CSS file?

**Comment by kocosmanberke** [comment]
It only changes the board color but background etc. is same

**Comment by uncenter** [comment]
Quite a lot of the userstyle is unthemed, but you are able to install it? @coldenate do you mind taking a look at the userstyle and seeing what can be fixed?

**Comment by kocosmanberke** [comment]
Changed all themes to default settings, problem solved.
