### ISSUE TITLE
Header and Buttons are Too Bright

### ISSUE THREAD

**Issue by Koba0117** [catppuccin/userstyles#1040]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:arch-wiki

### Describe your problem.

The header and the buttons are white and bright.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/112705243/b27fd821-69c5-411e-9fa6-c61a34cacf1d)
![image](https://github.com/catppuccin/userstyles/assets/112705243/31b4160b-397d-4d74-afba-c1f84c718899)

### What browser(s) are you seeing the problem on?

firefox 127.0.2

**Comment by isabelroses** [comment]
closed by https://github.com/catppuccin/userstyles/pull/1041.
