### ISSUE TITLE
phanpy: small color issues

### ISSUE THREAD

**Issue by stellophiliac** [catppuccin/userstyles#1079]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:phanpy

### Describe your problem.

some bits are unthemed or partly themed

### Attach screenshots.

<img width="612" src="https://github.com/user-attachments/assets/1a57fac0-130e-49ce-aa2e-5a5637ad5eda">

the `.replies-parent-link` button is still colored blue

<img width="630" src="https://github.com/user-attachments/assets/1a1fc75c-14c0-4ff0-bc57-8ca52d827405">

this top profile info box section seems to be a very slightly different color from `@base`

<img width="630" src="https://github.com/user-attachments/assets/b0320215-d578-4f8e-85a3-e3277d084eac">

since the original posts bar uses the accent color, there'd be issues when the accent is mauve or yellow

<img width="696" src="https://github.com/user-attachments/assets/ce82968a-7510-46bc-a7de-39f68ab22963">

in a "someone boosted or liked your post" notification, the show content and read more buttons + polls are unthemed until the preview is hovered (the user name looks possibly unthemed too)

also, some post previews very briefly flash unthemed when unhovered

https://github.com/user-attachments/assets/d0e3ff85-16d4-4902-8725-fcd51718edc1

### What browser(s) are you seeing the problem on?

Firefox v124.0.1-1

**Comment by stellophiliac** [comment]
also *just* noticed this right now, these little pill buttons have a blue border when hovered 

<img width="279" src="https://github.com/user-attachments/assets/b4fd7bb9-ed0b-486f-999c-fecb72e35df6">

**Comment by Guaxinim5573** [comment]
In the "someone boosted or liked your post" notification the websites applies a filter when not hovering the notification to have that "black and white" effect. The briefly flash you're seeing is probably the browser struggling to render the filter and colors at the same time when hovering.

Aside from that, all other stuff was fixed on #1136.

**Comment by sgoudham** [comment]
Closing since the aforementioned PR seems to have fixed issues listed here.
Please create another issue if you find that things are still unthemed, ideally a separate issue for any unique unthemed sections :+1:
