### ISSUE TITLE
SearXNG userstyle not working

### ISSUE THREAD

**Issue by hyperreal64** [catppuccin/userstyles#1088]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:searxng

### Describe your problem.

I have the CSP switch enabled. I have my SearXNG instance URL added to the list. The userstyle doesn't seem to work. It doesn't work on any SearXNG instance. The Stylus extension doesn't register that there is a userstyle for the site (the Stylus icon in the toolbar does not have the indicator). Other Stylus userstyles work though.

### What browser(s) are you seeing the problem on?

Firefox v128.0

**Comment by uncenter** [comment]
Working for me on https://search.bus-hit.me/:
![search bus-hit me_](https://github.com/user-attachments/assets/f5750d2d-7afc-4f15-9a82-f36bd303be0c)

What instance are you trying?

**Comment by hyperreal64** [comment]
My instance is https://searxng.hyperreal.coffee. I'm not sure how to debug this.

**Comment by uncenter** [comment]
Working on https://searxng.hyperreal.coffee/ for me?
Are you using the following to add it:
![image](https://github.com/user-attachments/assets/b9b1a276-5f87-4eb9-8c5f-9b1e746be253)

**Comment by hyperreal64** [comment]
Yes 
![Screenshot_20240719_122958](https://github.com/user-attachments/assets/20791733-2c95-441a-a951-7d7fb8a38f05)

**Comment by uncenter** [comment]
You need to add `/*` to the end of that line.

**Comment by hyperreal64** [comment]
Okay, that fixed it. Thanks.

**Comment by uncenter** [comment]
Great, apologies for the lack of instructions on that, we'll work on that!

**Comment by hyperreal64** [comment]
No worries! My brain parsed the sample text `*://site1.com/*` as a comment, so it wasn't obvious to me that it needed to be in that specific format lol.
