### ISSUE TITLE
Youtube progress bar and icon no longer being coloured by the accent colour

### ISSUE THREAD

**Issue by thedaedalus** [catppuccin/userstyles#1137]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

The video progress bar and the youtube logo are no longer being coloured 

### Attach screenshots.

![image](https://github.com/user-attachments/assets/06a35df1-5d92-4259-938d-c3d57259c3a8)
![image](https://github.com/user-attachments/assets/d40a35b4-a5f0-4abc-84f3-0660a1f685ef)

### What browser(s) are you seeing the problem on?

firefox 130.0a1

**Comment by uncenter** [comment]
Not seeing this on regular YouTube, so must be an issue with YouTube Premium or specifically YouTube in other regions.

**Comment by GenShibe** [comment]
can't replicate, i have premium and tested youtube.ca, both the logo and progress bar are themed 

<img width="162" alt="image" src="https://github.com/user-attachments/assets/f3e31328-3cec-4972-82db-6ff2142e9e11">
<img width="292" alt="image" src="https://github.com/user-attachments/assets/3b9774af-ce79-4ca5-aebd-01af255c91b0">


(style version 4.16, and arc version 127.0 fwiw)

**Comment by isabelroses** [comment]
> YouTube Premium

I have that, can confirm not the cause here.

> YouTube in other regions.

Not a region thing either.

<img width="137" alt="Screenshot 2024-07-31 at 8 28 43 AM" src="https://github.com/user-attachments/assets/f95b0294-10fb-4f69-8ae3-5a53e8b16e8d">

**Comment by uncenter** [comment]
To be sure you are on `v4.1.6` of the YouTube userstyle? The Stylus updater isn't great.

**Comment by thedaedalus** [comment]
Yup I am on v4.1.6 just to be sure I also used MS edge to check and got the same issues. 
![image](https://github.com/user-attachments/assets/c8903d4c-cbe2-4a52-aef6-6f4174878905)
