### ISSUE TITLE
Github top banner is light when not logged in

### ISSUE THREAD

**Issue by 500-internal-server-error** [catppuccin/userstyles#1145]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

The top bar is bright when not logged in, which probably looks fine on light mode but is a rather distracting flashbang due to the contrast otherwise.

### Attach screenshots.

When logged in all dark and fine:
![image](https://github.com/user-attachments/assets/cbd17b42-0010-49f9-83a8-f9a0cbe6adf8)
When not logged in I get flashbanged:
![image](https://github.com/user-attachments/assets/6e1339f2-ba73-4101-bc28-ca386408fdb3)

### What browser(s) are you seeing the problem on?

Firefox v128.0.3

### Any additional comments?

Maybe this is how the theme has always looked, but as a new user I find it to be quite an odd choice given the painful spike in contrast relative to the rest of the easy-on-the-eyes theme.

Perhaps it isn't intended to be that way, given the default github theme doesn't have this contrast spike on their dark mode?

**Comment by uncenter** [comment]
This is an issue with GitHub's HTML, where they explicitly set the theme to be light mode in that section of the page but invert it or something on their end:
![CleanShot 2024-07-31 at 12 34 06@2x](https://github.com/user-attachments/assets/fac07d61-6b6f-459d-bde0-235ef8b74a15)
It is properly themed with Latte though so I have no plans of changing this.

**Comment by uncenter** [comment]
(Duplicate of #954 as well).
