### ISSUE TITLE
Google highlighting hard to read

### ISSUE THREAD

**Issue by smergner1** [catppuccin/userstyles#1147]
### Is there an existing issue outlining your problem?

- [x] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:google

### Describe your problem.

Google highlighted answers hard to read using Mocha and Sky accent.

### Attach screenshots.

![image](https://github.com/user-attachments/assets/4019e55a-bad5-466d-8c93-1035c3c65859)

### What browser(s) are you seeing the problem on?

Librewolf latest release

**Comment by isabelroses** [comment]
I can't seem to reproduce that. Sometimes stylus is a bit strange... do you mind reinstalling the userstyle.
![image](https://github.com/user-attachments/assets/ee768e4f-2335-4080-9547-4484ad3f109a)

**Comment by GenShibe** [comment]
I think i know what the issue is here, you're using a dark theme on light mode, and that's why it's being weird

**Comment by mca10** [comment]
@GenShibe It also happens with dark/dark combos. PR is up though!

https://github.com/user-attachments/assets/3ce79aaa-b00f-4952-bc29-4da967aee7b7
