### ISSUE TITLE
skiff: Website doesn't exist anymore

### ISSUE THREAD

**Issue by coopw1** [catppuccin/userstyles#1192]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:skiff

### Describe your problem.

[Skiff](https://skiff.com/) was bought out by notion and the mail page no longer exists

### What browser(s) are you seeing the problem on?

Chromium: 127.0.6533.100

**Comment by sgoudham** [comment]
As discussed on discord, it makes sense to remove the `skiff` userstyle directory from this repository as well other relevant metadata relating to the userstyle.

Sorry to hear that your userstyle no longer exists but if you don't maintain other userstyles in this repository then your maintainer permissions will also be revoked 👍

**Comment by coopw1** [comment]
Still have one other one I maintain luckily - thanks for the help!
