### ISSUE TITLE
Change accent color for all styles

### ISSUE THREAD

**Issue by sineptic** [catppuccin/userstyles#1210]
### Is there an existing issue outlining your problem?

- [x] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

I can change accent color for 1 theme, but it's too long. Can I change it for all at once?

**Comment by uncenter** [comment]
Mentioned in https://github.com/catppuccin/userstyles/releases/tag/all-userstyles-export (which is linked on our readme as the recommended installation method).

**Comment by sineptic** [comment]
You say, that only approach is import themes a lot of times to change accent color?

**Comment by uncenter** [comment]
How else would you do it? I can add a list of checkboxes so that you can uncheck certain or all userstyles to that generator website?

**Comment by uncenter** [comment]
For the record - I only visit half the sites we have userstyles for, and I use the import generator method. Way easier.

**Comment by sineptic** [comment]
Ok, thank you. I have problem, that in some sites I slightly modify theme. No problem, I just don't want use local version.
