### ISSUE TITLE
Automate setting up a new userstyle

### ISSUE THREAD

**Issue by thismoon** [catppuccin/userstyles#1214]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

Currently, when creating a new userstyles, users have to follow the steps in https://github.com/catppuccin/userstyles/blob/main/docs/userstyle-creation.md. some of which can be automated.
I suggest adding a new cli script/tool that:

- takes the website name as input
- creates a `styles/<name-of-website>` folder in lower-kebab-case
- copies the template folder content into the new folder
- modify the usercss metadata by replacing `<port-name>` with the website name (capitalized or lower-kebab-case when appropriate)

It probably needs to be built using typescript like the other scripts but i'm unfamiliar with it

**Comment by uncenter** [comment]
I don't think we currently plan on adding that functionality to this repository directly. I've made a separate CLI tool you can use though, https://github.com/uncenter/purr! The command for what you are describing would be `purr init userstyle`, though there is lots more functionality :)
