### ISSUE TITLE
Make "All Userstyles Import Generator" more visible

### ISSUE THREAD

**Issue by nikitarevenco** [catppuccin/userstyles#1254]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

I think that most people will download every single userstyle. And downloading them by using the All Userstyles Import Generator is probably the most common way, so instead of making it a 2-step process, let's make it a 1 step process instead.

In the README, under "All Userstyles", use instructions like this:

1. Use [All Userstyles Import Generator](https://ctp-aui.uncenter.dev/)
1. Open Stylus "Manage" page
2. Locate backup and select import, import the downloaded file

if the Import Generator already includes the latest changes, then there it might not be necessary to link to the github releases page

**Comment by GaelanVenturi** [comment]
I agree, this is something that I have done and would greatly help a lot of people I think.

**Comment by uncenter** [comment]
We've discussed this in the Catppuccin Discord server (publically available if you want to join) and decided that we will move the instructions to the README instead of on the release page for clarity and version control. I will also look at cleaning up the usage/installation process overall in the README (might even be nice to have installation links next to each userstyle in the list, to avoid having to go to each individual readme?). We won't be linking to https://ctp-aui.uncenter.dev/ however as it is not officially part of userstyles, rather a side project of mine. It will still be a tip in the instructions, so functionally the same. Thanks for bringing this to our attention!

**Comment by nikitarevenco** [comment]
> We've discussed this in the Catppuccin Discord server (publically available if you want to join) and decided that we will move the instructions to the README instead of on the release page for clarity and version control. I will also look at cleaning up the usage/installation process overall in the README (might even be nice to have installation links next to each userstyle in the list, to avoid having to go to each individual readme?). We won't be linking to https://ctp-aui.uncenter.dev/ however as it is not officially part of userstyles, rather a side project of mine. It will still be a tip in the instructions, so functionally the same. Thanks for bringing this to our attention!

Sweet! Should I PR?

**Comment by uncenter** [comment]
> > We've discussed this in the Catppuccin Discord server (publically available if you want to join) and decided that we will move the instructions to the README instead of on the release page for clarity and version control. I will also look at cleaning up the usage/installation process overall in the README (might even be nice to have installation links next to each userstyle in the list, to avoid having to go to each individual readme?). We won't be linking to [ctp-aui.uncenter.dev](https://ctp-aui.uncenter.dev/) however as it is not officially part of userstyles, rather a side project of mine. It will still be a tip in the instructions, so functionally the same. Thanks for bringing this to our attention!
> 
> Sweet! Should I PR?

Thanks for offering! I think I'll take care of it since I have a few other improvements in mind!

**Comment by uncenter** [comment]
Sorry for the delay, fried my computer with uncommitted changes earlier this week and only now have another primary machine up and running. Hopefully can get these changes PRed this weekend!
