### ISSUE TITLE
Pypi Links cannot be seen

### ISSUE THREAD

**Issue by Kathund** [catppuccin/userstyles#1344]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:pypi

### Describe your problem.

All Links are fully broken and cannot be seen

### Attach screenshots.

https://github.com/user-attachments/assets/671a13b6-8d16-42fb-be7e-9722c6c5bf05

### What browser(s) are you seeing the problem on?

Brave 1.69.168 Chromium: 128.0.6613.138

**Comment by uncenter** [comment]
I'm not able to reproduce this on Google Chrome 129.0.6668.70. What version of the userstyle are you on?

**Comment by trinkey** [comment]
this has been fixed a long time ago, you need to update the userstyle version

![image](https://github.com/user-attachments/assets/1c72e842-a193-4f53-808e-b1d23aa0fe7f)

**Comment by Kathund** [comment]
> this has been fixed a long time ago, you need to update the userstyle version. the latest version is 0.0.7 ![image](https://private-user-images.githubusercontent.com/97406176/373064764-1c72e842-a193-4f53-808e-b1d23aa0fe7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5MjcyMTIsIm5iZiI6MTcyNzkyNjkxMiwicGF0aCI6Ii85NzQwNjE3Ni8zNzMwNjQ3NjQtMWM3MmU4NDItYTE5My00ZjUzLTgwOGUtYjFkMjNhYTBmZTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDAzNDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlOTUxODA1ZGY4YjdlNTczNDVmNzVhMGU0MmU4Y2VjNjAyMDVhZjZmYWY0YzQ3ZDQxMTFmMzgwOGZkM2MwNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3XZFreA3KBUs_ODPLOcBxLfavC43LSyp2nqekGn6GHc)

Turns out the issue was with the version of Styles I was using not the theme version. They were all up to date because I removed them all and readded them to make sure. Not sure how I managed to use a version of Styles from 2018
