### ISSUE TITLE
Can't push my userstyle to fork

### ISSUE THREAD

**Issue by claymorwan** [catppuccin/userstyles#1379]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

Been trying to push my userstyle to the repo to contribute, but I keep getting this error.
```
fatal: protocol error: bad line length 192
send-pack: unexpected disconnect while reading sideband packet
```
I tried asking on the git reddit but nothing, maybe it's a problem with the repo (I have git lfs installed).

**Comment by uncenter** [comment]
Can you send more of the error? If you are in the Catppuccin Discord server we can discuss more easily there as well.

**Comment by uncenter** [comment]
Seems like it might be a network issue? https://stackoverflow.com/questions/66366582/github-unexpected-disconnect-while-reading-sideband-packet

**Comment by claymorwan** [comment]
tried that one before and didn't work, Imma join the discord

**Comment by uncenter** [comment]
Resolved (in Discord) by unstaging and restaging and/or running `git config --global http.postBuffer 157286400`.
