### ISSUE TITLE
mbBook not loading

### ISSUE THREAD

**Issue by mambucodev** [catppuccin/userstyles#1399]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:mdbook

### Describe your problem.

My theme for mdBook is not loading in any way...

### Attach screenshots.

![image](https://github.com/user-attachments/assets/93df8fdf-6dd2-4aee-9759-ef327e02082f)

### What browser(s) are you seeing the problem on?

Firefox v131.0.3

**Comment by mambucodev** [comment]
I think mantainer is @uncenter (sorry for mention)

**Comment by uncenter** [comment]
Not able to reproduce on Chrome.

![CleanShot 2024-10-25 at 11 20 23](https://github.com/user-attachments/assets/2019cf20-5902-44e7-8e20-09b721910108)

Is your Stylus lighting up - are you sure it is enabled on the page? Have you modified the settings or the userstyle at all? Have you installed it?

**Comment by mambucodev** [comment]
Yes, I'm using stylus and it's working for my other 20 websites.
![image](https://github.com/user-attachments/assets/34a3247d-0745-42f8-9f0d-06a37e2daa47)
The theme is active, and still, it's not working...

**Comment by uncenter** [comment]
Copied and pasted what? That's not how our documentation instructs you to install userstyles.

**Comment by mambucodev** [comment]
Oh... Well I just already knew how stylus works so I copied the whole .css file and pasted it into a new stylus stylesheet, and it worked for pretty everything, also recognising websites, updateURL, and so on.

**Comment by mambucodev** [comment]
I'd like to clarify that I used this method purely because I didn't want ALL userstyles to be imported into Stylus, but just the websited I prefered. If you need me to use the import.json method, I'll do so.

**Comment by uncenter** [comment]
That's not the only method we give though? Have you tried https://github.com/catppuccin/userstyles#individual-userstyles?

**Comment by mambucodev** [comment]
Sorry, didn't notice it, I'll try it right away and let you know.

**Comment by uncenter** [comment]
Can confirm I'm also not experiencing this issue on v131.0b2 of Firefox (Developer Edition) or as originally commented on Chrome v129.

**Comment by mambucodev** [comment]
I'm really sorry for losing your time...
I was setting up my whole PC to be catppuccin, and didn't notice that the **DarkReader** extension was active and it was overlapping the Stylus theme. Now everything works gorgeously... I'm really sorry for disturbing you for my error...

**Comment by uncenter** [comment]
No worries at all! We can add a note to the README reminding users about userstyle and Dark Reader conflicts - there also is a draft PR to add a filter list to ignore pages with userstyles already.
