### ISSUE TITLE
Feature request: a solid black background for a video player when in full screen

### ISSUE THREAD

**Issue by andreiborisov** [catppuccin/userstyles#1412]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

I think it would make for a much better viewing experience if the video background in full screen will be a solid black color like on vanilla YouTube.

Solid black is preferable for a video background due to superior contrast in my opinion.

### Attach screenshots.

![Dragon Age_ The Veilguard - PS5_Xbox Series X_S Tech Review - Impressive Visuals](https://github.com/user-attachments/assets/cae6f66b-3e47-480f-a849-2dd5634d468a)

### What browser(s) are you seeing the problem on?

Chromium v130.0.6723.70

**Comment by uncenter** [comment]
![CleanShot 2024-10-30 at 11 22 00](https://github.com/user-attachments/assets/f7304b13-0cf9-45ec-b297-1cdad7ca475b)

There is a setting for the userstyle that enables this.
