### ISSUE TITLE
Google Photos: rectangular bar that partially covers the image in Google Photos

### ISSUE THREAD

**Issue by duckaleuze** [catppuccin/userstyles#1414]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:google-photos

### Describe your problem.

as the title says when I activate the catpuccin userstyle a rectangular bar appears and covers part of the image

### Attach screenshots.

![image](https://github.com/user-attachments/assets/6d700790-f662-458a-905e-627e0ff91937)

### What browser(s) are you seeing the problem on?

Firefox 132.0

**Comment by GenShibe** [comment]
wow, i'm surprised it took someone this long to notice lol, i'll fix this rn

**Comment by duckaleuze** [comment]
I just started using these userstyles about a week ago, and I quickly noticed this bug. It's weird to me that not many people use these styles, I really love them
