### ISSUE TITLE
fix twitch dashboard pls

### ISSUE THREAD

**Issue by Fan4eGGG** [catppuccin/userstyles#1434]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:twitch

### Describe your problem.

in dashboard style is broken, pls fix

### Attach screenshots.

![image](https://github.com/user-attachments/assets/ec5449cf-0819-467d-86a1-5d60902b51b7)

### What browser(s) are you seeing the problem on?

opera one

**Comment by mxgic1337** [comment]
If you are using Dark Reader or some kind of dark mode extension, try disabling it.

**Comment by Fan4eGGG** [comment]
oh, thank u man

**Comment by Fan4eGGG** [comment]
One more pls, the view timer is not visible on any theme.
is there any way to fix this?
![image](https://github.com/user-attachments/assets/4f1f1d8c-edd4-4eb5-a1fb-5ed44b59d024)

**Comment by mxgic1337** [comment]
This should fix it: #1439

**Comment by Fan4eGGG** [comment]
my hero

**Comment by Fan4eGGG** [comment]
VOD category previews (posters and titles) are too dark imo
![Screenshot_1](https://github.com/user-attachments/assets/efd14e18-58c5-41e8-88a2-fa335be9a53e)

is it okay if I post here any mistakes I've noticed?

**Comment by mxgic1337** [comment]
I think you should create a new issue for every mistake you find.
This should fix your issue: #1442

**Comment by uncenter** [comment]
> I think you should create a new issue for every mistake you find.

Actually we would prefer if @Fan4eGGG you could look at the PRs @mxgic1337 opens to fix your issues before we merge them and confirm there is nothing else left unthemed for you.
