### ISSUE TITLE
YouTube: missing colors for search box and search suggestions box

### ISSUE THREAD

**Issue by ashish0kumar** [catppuccin/userstyles#1486]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

The colors of the search box and suggestions box are broken

The search box and search suggestions box should display the correct colors for the respective Catppuccin flavors.

### Attach screenshots.

![Screenshot 2024-12-11 183040](https://github.com/user-attachments/assets/4b406f20-4db8-4134-b9cd-addc4880cc15)

### What browser(s) are you seeing the problem on?

Firefox v133.0

**Comment by uncenter** [comment]
Not reproducible on my end. Possibly https://github.com/catppuccin/userstyles/pull/1419 or regional difference.

**Comment by PassiHD2004** [comment]
> Not reproducible on my end. Possibly #1419 or regional difference.

![image](https://github.com/user-attachments/assets/8dd9b51f-1a20-47ce-8558-378c422adccb)

reproducible on my end

Firefox developer edition v134.0b9

**Comment by isabelroses** [comment]
Seems to be reproducible for me on arc 131.0.6778.109, region GB. 
![{FB57F1FE-8B12-41D7-9009-ED1A2B6741A8}](https://github.com/user-attachments/assets/bbde100c-0ae2-445e-9b6e-ae920479ad9f)

**Comment by PassiHD2004** [comment]
I also just tested on Cromite v131.0.6778.86 with another account as well as my main, still reproducible
