### ISSUE TITLE
YouTube: Live chat replay is not styled

### ISSUE THREAD

**Issue by nyxiereal** [catppuccin/userstyles#1492]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

The Live chat replay section is not styled. I expected it to match the colors (see screenshot below)

### Attach screenshots.

![image](https://nextcloud.fuckingbitch.eu/apps/files_sharing/publicpreview/F96fi7KRaZqEzxE?file=/&fileId=302&x=1920&y=1200&a=true&etag=8ce1c37517d5391bfff941239931a6b6)

### What browser(s) are you seeing the problem on?

Floorp (based on Firefox ESR, v128)

**Comment by uncenter** [comment]
Just making sure, you are on the latest version? I thought this was fixed in https://github.com/catppuccin/userstyles/pull/1483.

**Comment by nyxiereal** [comment]
YouTube moment, I submitted my fix in the pr above.
