### ISSUE TITLE
Create `catppuccin/userstyles` GitHub Team

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/userstyles#15]
## Description

It's been raised before that it would be nice to have a logical grouping of all the maintainers for userstyle ports as they are quite popular and only growing. We should add a GitHub team and verify that they're all happy to be in this.

## Acceptance Criteria

- [x] Ensure that all userstyle port maintainers are under one team
  - [x] Team is created
  - [x] All current members listed in `CODEOWNERS` are added
- [x] Verify that the `CODEOWNERS` file is accurate
  - [x] Ping them on GitHub and verify that they're happy to still be added (I guess this doubles as a userstyle maintainer audit)
- [x] Make sure that everyone understands that they should be contributing to the central repository instead of the individual ones

**Comment by sgoudham** [comment]
## Hiya Everyone! 
### This ping is related to userstyles transition raised in https://github.com/catppuccin/community/discussions/4

The plan from now on for Catppuccin Stylus Userstyles is to migrate them all into one repository to make them easier to maintain. This repository should now be where it's more or less ready to be transferred to the central organisation and redirect all the links from individual repositories to this main one.

We have aggregated all styles [here](https://github.com/catppuccin-rfc/userstyles/tree/main/styles) while refactoring them to make them one single file where possible, please check through your ports directory and check if you're okay with it. Before I transfer the repository across, I wanted to ping everyone to make sure they understand and if they are okay with this. Here is our most up-to-date information on who maintains what:

**If you would like to be removed from being an official "maintainer" of one of these ports, please comment down below and we will do so**. If you are happy then please give a thumbs-up reaction to this comment

| Maintainers    | Ports                                                          |
| -------------- | -------------------------------------------------------------- |
| @anubisnekhet  | `anilist`, `lastfm`, `nitter`                                    |
| @ndsboy        | `brave-search`                                                  |
| @jn-sena       | `cinny`                                                         |
| @watatomo      | `deepl`, `ichi.moe`                                             |
| @ryanccn       | `vercel`, `elk`, `searxng`, `tutanota`                           |
| @Pocco81       | `github`                                                        |
| @GlowingUmbreon| `github`                                                        |
| @justTOBBI     | `codeberg`                                                      |
| @andreasgrafen | `github`, `invidious`, `libreddit`, `mastodon`, `searxng`         |
| @lucasmelin    | `hacker-news`                                                   |
| @Gingeh        | `lastfm`                                                        |
| @isabelroses   | `youtube`, `mastodon`, `twitch`                                  |
| @thismoon      | `modrinth`                                                      |
| @alaidriel     | `nixos-search`                                                  |
| @soya-daizu    | `proton`                                                        |
| @jayylmao      | `reddit`                                                        |
| @rubyowo       | `reddit`, `wikiwand`                                            |
| @Sekki21956    | `searxng`                                                       |
| @nekowinston   | `searxng`                                                       |
| @GitMuslim     | `twitch`                                                        |
| @tnixc         | `wikiwand`                                                      |

## Next Steps

Once people are informed / happy, we will: 
- Transfer the repository to the central organisation
- Update the links in the main repository to the userstyles repository. This will minimise traffic to existing userstyle repositories
- Start archiving the individual userstyle repositories as noted in the community discussion at the top of this comment. I will probably start doing this in the order of the ports listed in the styles directory. 

We have also created a GitHub team for userstyles here: https://github.com/orgs/catppuccin/teams/userstyles/members (unsure if others can see) that will be granted access to the main repository.

**Comment by Gingeh** [comment]
Please remove me as a maintainer for `lastfm`

**Comment by isabelroses** [comment]
This list is also not done by the maintainers but rather the thanks to section so there maybe confusion and misunderstandings there, for anyone that's not expecting themesleves to be mentioned in certain ports.

**Comment by sgoudham** [comment]
Based on the above comment, we'll edit the README template to mention the "Current Maintainers" and also include a separate section for previous maintainers and/or general contributions.

**Comment by GitMuslim** [comment]
@sgoudham Looks good

**Comment by nekowinston** [comment]
Please remove me from searxng and add me to invidious.

**Comment by rubyowo** [comment]
pls remove from reddit & wikiwand kthx 👍🏼

**Comment by sgoudham** [comment]
Thanks everyone for replying again!
We've transferred over the repository and gave everyone in the GitHub maintain permissions :tada: 

We''ll now start the process of reviewing and merging https://github.com/catppuccin/catppuccin/pull/1981. @nekowinston will be focusing on #16 and hopefully we can wrap this migration up!
