### ISSUE TITLE
Doesn’t work at all?

### ISSUE THREAD

**Issue by Geobert** [catppuccin/userstyles#159]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:mastodon

### Describe your problem.

I’ve added my instance to the list and Stylus is showing the style being active but I can’t see any changes.
Using Firefox 116, and I tried setting the style to Dark in Firefox’s settings.

### What browser(s) are you seeing the problem on?

Firefox 116

**Comment by isabelroses** [comment]
> I’ve added my instance to the list 

could you share your instance, sometimes it can be caused by this. Otherwise ill take a look when I get a chance

**Comment by Geobert** [comment]
Thanks for your answer!
The instance is piaille.fr

**Comment by night-lake** [comment]
appears to also occur on tech.lgbt

**Comment by Geobert** [comment]
It seems that it broke again today, same instance but Firefox 117

**Comment by Geobert** [comment]
Forget last comment, after a reboot, it works again. Some Firefox hiccups I think
