### ISSUE TITLE
Archive Userstyle Repositories + Transfer Issues

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/userstyles#16]
## Description

Once the central repository is ready and maintainers have been verified and informed officially about this new repository. We should proceed with our plan and archive the "old" userstyle repositories and transfer their respective issues over.

## Acceptance Criteria 

For each port we should:
1. Update `README.md` to point towards the new location
2. Issues are migrated over and labelled properly
3. Officially Archived

- [x] `anilist`
- [x] `lastfm`
- [x] `nitter`
- [x] `brave-search`
- [x] `cinny`
- [x] `deepl`
- [x] `ichi.moe`
- [x] `vercel`
- [x] `elk`
- [x] `searxng`
- [x] `tutanota`
- [x] `github`
- [x] `codeberg`
- [x] `invidious`
- [x] `libreddit`
- [x] `mastodon`
- [x] `hacker-news`
- [x] `youtube`
- [x] `twitch`
- [x] `modrinth`
- [x] `nixos-search`
- [x] `proton`
- [x] `reddit`
- [x] `wikiwand`

**Comment by rubyowo** [comment]
is transferring issues even possible?

**Comment by nullishamy** [comment]
> is transferring issues even possible?

yes. cross org transfers may need to be investigated though.

**Comment by sgoudham** [comment]
There'll be nothing cross org since we'll be transferring this repository into the main organisation before the issues are transferred over @nullishamy

**Comment by nullishamy** [comment]
Cool, should work fine then.
