### ISSUE TITLE
Youtube Userstyle Not Loading Properly

### ISSUE THREAD

**Issue by moqqa** [catppuccin/userstyles#167]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

Upon opening any youtube link whilst using Mocha or Latte, the theme seems to break. Various elements on the page having only portions of the theme applied and fonts being miscoloured.

### Attach screenshots.

![Screenshot 2023-08-13 at 00-03-32 These Switches from Loobed Switches are a GAME CHANGER Pines Switches Review](https://github.com/catppuccin/userstyles/assets/71618230/3873f7d1-37a1-4f4b-8132-2949645fbd13)
![Screenshot 2023-08-13 at 00-04-17 These Switches from Loobed Switches are a GAME CHANGER Pines Switches Review](https://github.com/catppuccin/userstyles/assets/71618230/779988b8-e93a-4007-93f9-f16a86dff57e)

### What browser(s) are you seeing the problem on?

Firefox v116.0.2

**Comment by isabelroses** [comment]
This is due to YouTube's ambient mode, disabling it should fix the issue.

**Comment by isabelroses** [comment]
I can't seem to replicate this on firefox, what version of the theme do you have?

**Comment by moqqa** [comment]
version 3.0.9, turning off ambient mode was a fix but unsure as to why stylus rendered it the way that it did.

**Comment by ishandandekar** [comment]
Hi @moqqa , I am new to this themeing world, could you please tell how did you apply this theme to YouTube?

**Comment by isabelroses** [comment]
> how did you apply this theme to YouTube?

Please follow the instructions [here](https://github.com/catppuccin/userstyles?tab=readme-ov-file#%EF%B8%8F-install)

**Comment by ishandandekar** [comment]
I still can't figure the "Install the theme" step. Could you please elaborate on this further?

**Comment by isabelroses** [comment]
> I still can't figure the "Install the theme" step. Could you please elaborate on this further?

So head to the page `https://github.com/catppuccin/userstyles/raw/main/styles/<name>/catppuccin.user.css` but instead of `<name>`  its the name of the port, so for youtube its `https://github.com/catppuccin/userstyles/raw/main/styles/youtube/catppuccin.user.css`

**Comment by bernzrdo** [comment]
For some weird reason, it's not working again! 
![image](https://github.com/catppuccin/userstyles/assets/27358071/2c0ae412-e4ca-4ef0-9d6a-d52251e35bb1)
An easy fix would be something along the lines of
```css
#cinematics {
  mix-blend-mode: ligthen;
}
```
