### ISSUE TITLE
Issues with new github tree explorer interface

### ISSUE THREAD

**Issue by ZerdoX-x** [catppuccin/userstyles#202]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

Mocha (Pink accent) theme. Github theme is light default, untouched.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/49815452/37bd4405-9623-4c6b-a542-ee782a4b0f65)

### What browser(s) are you seeing the problem on?

LibreWolf 117.0-1

**Comment by ZerdoX-x** [comment]
Also 
![image](https://github.com/catppuccin/userstyles/assets/49815452/4d96dd05-4a9b-4b36-917f-f0321d28d307)

**Comment by isabelroses** [comment]
Try using the dark mode (from GitHub themesleves), other then that the rest of the issue are likely due to this feature being in beta and will eventually be themed.

**Comment by justTOBBI** [comment]
Can confirm, using the Default Dark Theme fixes the 'error'

**Comment by uncenter** [comment]
These images aren't visible to me anymore? Maybe we make the recommendation to just stick to GitHub's dark mode?
