### ISSUE TITLE
Twitch white chat & dark "browse" link (near main twitch logo)

### ISSUE THREAD

**Issue by ZerdoX-x** [catppuccin/userstyles#203]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:twitch

### Describe your problem.

Snippet from devtools
```
.tw-root--theme-light .chat-room {
  background: #fff;
}
```

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/49815452/c6ae21b3-6d05-47f2-a010-e58050365af2)

### What browser(s) are you seeing the problem on?

Firefox 117

**Comment by isabelroses** [comment]
If you enable twitch's default dark mode then the chat's theming will fix.

**Comment by ZerdoX-x** [comment]
Yeah. The problem is I often don't login into my accounts when it's not needed. Almost all of my browser's data get wiped when I quit. And even If I login, chances that theme is stored in localstorage, not on server.

I think theme should be usable without login and changing default twitch theme
