### ISSUE TITLE
QuteBrowser Stylesheets support

### ISSUE THREAD

**Issue by cronyakatsuki** [catppuccin/userstyles#207]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

Is there any possibility for this repo to add qutebrowser stylesheet support?

**Comment by isabelroses** [comment]
This really just depends if there is any pre existing tools to do so.

**Comment by isabelroses** [comment]
> The issue is that qutebrowser only accepts css, not less. So it requires some fiddling to convert it.

For this the user can compile the less down to css, (see https://lesscss.org)

> Either it's a note in the README on how to do it for the individual user who wishes to implement a style, or we'll have duplicate files to maintain for each site...

I think there could be a note on the main README but we would need to do it in some form of clean way.

**Comment by cronyakatsuki** [comment]
Guess we will need to wait for qutebrowser to fix issue qutebrowser/qutebrowser#3636 for this to be possible in a clean way

**Comment by isabelroses** [comment]
Hi there, after a lot more thought, this is won't be supported within the near future. If you did at some point want to use the theme from userstyles you could compile them down from less. I'm closing this as not planned unless something changes. Thanks for your patience.
