### ISSUE TITLE
YouTube light/dark toggle

### ISSUE THREAD

**Issue by uncenter** [catppuccin/userstyles#220]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

The YouTube userstyle (appears to?) recommend setting the YouTube appearance to light - maybe it is easier to style it in light mode - but provides no way to *use* dark mode. I'm suggesting an additional setting to configure that. Something like...
```css
/* ==UserStyle==
...
@var select theme "Theme" ["light:Light", "dark:Dark", "system:System*"]
...
==/UserStyle== */
@-moz-document regexp('https?:\\/\\/(?!gaming\\.)(?!consent\\.)(?!vr\\.)(?!music\\.)(?!tv\\.)(?!artists\\.)(?!studio\\.).*youtube(?!kids\\.).*\\.com\\/(?!premium|howyoutubeworks).*$') {
  #oled(@oledOn);
  #logo(@logo);

  when (@theme ='dark') {
    #catppuccin(@darkFlavor, @accentColor);
  }
  when (@theme ='light') {
    #catppuccin(@lightFlavor, @accentColor);
  }
  when (@theme ='system') {
    @media (prefers-color-scheme: light) {
      #catppuccin(@lightFlavor, @accentColor);
    }
    @media (prefers-color-scheme: dark) {
      #catppuccin(@darkFlavor, @accentColor);
    }
  }
}
```

I tried to do it myself (above) but I couldn't figure out how to check the values of variables.

### What browser(s) are you seeing the problem on?

Arc 117.0.5938.88 (Chromium)

**Comment by isabelroses** [comment]
Currently i use youtube in dark mode, 
![image](https://github.com/catppuccin/userstyles/assets/71222764/0c0f9b94-35ab-412c-bf35-8d80fa1fec93)
So i am unsure what your getting at here.

**Comment by uncenter** [comment]
![Screenshot 2023-09-24 at 12 44 27 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/f7693870-6dde-4bf3-96f1-bc00948845a7)
@isabelroses then what is the point of this?

**Comment by isabelroses** [comment]
> ![Screenshot 2023-09-24 at 12 44 27 (Arc)](https://user-images.githubusercontent.com/47499684/270178909-f7693870-6dde-4bf3-96f1-bc00948845a7.png) @isabelroses then what is the point of this?

Oh, i think thats some left over reminisce from the old theme. I'll fix that now

**Comment by uncenter** [comment]
Oh okay sorry
