### ISSUE TITLE
Github index (home) page warning "Unsupported Github Theme" which blocks "Sign in" and "Sign up" buttons.

### ISSUE THREAD

**Issue by ZerdoX-x** [catppuccin/userstyles#231]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

Log out of your account. Go to https://github.com/  
Page seems to look ok, cannot reference any huge problems with colors here, but this warning covers "Sign in" and "Sign up" buttons which may be very annoying.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/49815452/250cffad-0ec9-474a-9042-7c26da1cc3a9)

### What browser(s) are you seeing the problem on?

Librewolf 117

**Comment by isabelroses** [comment]
Temporarily disable the theme, then sign in.

**Comment by ZerdoX-x** [comment]
> Temporarily disable the theme, then sign in.

Of course this works as a workaround. But this is indeed not a solution.

**Comment by ZerdoX-x** [comment]
But why do we even need this warning on a default home page?

**Comment by isabelroses** [comment]
> But why do we even need this warning on a default home page?

The warning exists only when the basic light or dark mode theme is not applied, this could cause issue reports that could be impossible for us to fix.

**Comment by ZerdoX-x** [comment]
> The warning exists only when the basic light or dark mode theme is not applied, this could cause issue reports that could be impossible for us to fix.

Strange that this userstyle doesn't support github home page as it's displayed with no theme configuration. Do we just ignore this case from now?

**Comment by isabelroses** [comment]
> Strange that this userstyle doesn't support github homepage as it's displayed with no theme configuration. Do we just ignore this case from now?

I found a way to ignore logged out accounts and the homepage when logged in, pushing the fix now.

**Comment by ZerdoX-x** [comment]
Thanks, that's all good now
