### ISSUE TITLE
hoppscotch: webp images broken

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/userstyles#236]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:hoppscotch

### Describe your problem.

When I added hoppscotch I messed up the individual flavor screenshots. Should be an easy fix for some Beginners for the Hacktoberfest ;)

### What browser(s) are you seeing the problem on?

every Browser Version

**Comment by rubyowo** [comment]
![image](https://github.com/catppuccin/userstyles/assets/105302757/ef8505a6-07e0-4998-a8b7-db3930d86681)
they all work though?

**Comment by justTOBBI** [comment]
They dont on the app... :(

**Comment by rubyowo** [comment]
L github mobile

**Comment by sgoudham** [comment]
Closing as this is related to GitHub Mobile's functionality
