### ISSUE TITLE
startpage: catwalk image is misaligned

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/userstyles#238]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:startpage

### Describe your problem.

The catwalk generated image does not line up with the text correctly (see screenshot)

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/58985301/8b8e95cf-f10d-45ac-b247-19c74e89eef1)

### What browser(s) are you seeing the problem on?

N/A

**Comment by isabelroses** [comment]
closed by https://github.com/catppuccin/userstyles/pull/247
