### ISSUE TITLE
Pinned message background overlaps chat box

### ISSUE THREAD

**Issue by fruzitent** [catppuccin/userstyles#242]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:twitch

### Describe your problem.

Weird layout somewhere around `div.community-highlight-stack__card` or `div.pinned-chat__highlight-card` when pinned message is expanded.

### Attach screenshots.

![image_2023-10-02_02-54-49](https://github.com/catppuccin/userstyles/assets/40008647/9936cb5b-0a34-4885-9a87-3a3a445272e4)
![image_2023-10-02_02-54-48](https://github.com/catppuccin/userstyles/assets/40008647/b54740fa-2845-4030-93e1-5ba87702ec1f)

### What browser(s) are you seeing the problem on?

Mozilla Firefox for Arch Linux 118.0.1 (64-bit)

**Comment by isabelroses** [comment]
I thinks this same issue occurs on normal unaltered twitch as well.

**Comment by isabelroses** [comment]
> I thinks this same issue occurs on normal unaltered twitch as well.

Seen here:
![image](https://github.com/catppuccin/userstyles/assets/71222764/bbef2d11-e1f1-4638-bbec-6ac097356b91)

Therefore i will leave this issue to twitch and close this issue as unplanned.
