### ISSUE TITLE
GitHub userstyle is incompatible

### ISSUE THREAD

**Issue by icebarf** [catppuccin/userstyles#246]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

There is a non-removable red-colored popup saying that my installed catppuccin flavor is incompatible. I have tried installing the default one

### Attach screenshots.

![Screenshot_20231003_145356](https://github.com/catppuccin/userstyles/assets/25560263/b3773e47-25d0-4a33-8146-be217c513c49)

### What browser(s) are you seeing the problem on?

Firefox v112.0.2

**Comment by nekowinston** [comment]
This refers to the default light/dark theme [here](https://github.com/settings/appearance):
![2023-10-03-113133@2x](https://github.com/catppuccin/userstyles/assets/79978224/a82a4870-aae0-475a-902f-4a36bc7b6c2f)

**Comment by icebarf** [comment]
Thank you @nekowinston

**Comment by justTOBBI** [comment]
Why is it so hard for people to read the complete hint?

**Comment by icebarf** [comment]
> Why is it so hard for people to read the complete hint?

The language is unclear, don't be an arse.

**Comment by sgoudham** [comment]
Hi @icebarf, sincere apologies on behalf of justTobbi's comments. 

I agree with you that the original language was confusing, I've tried to make the language clearer in #252 by explicitly mentioning the GitHub Appearance settings, I hope this will avoid future users from running into the same confusion :+1:

**Comment by icebarf** [comment]
Thank you @sgoudham. I appreciate you making everything clear ^_^

**Comment by justTOBBI** [comment]
Seems like I got quite worked up last night for no reason.
Sincere apologies, I'll do my best to not let that happen again.
