### ISSUE TITLE
Assorted Unthemed Github Elements

### ISSUE THREAD

**Issue by GenShibe** [catppuccin/userstyles#285]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

the search bar, the drop downs when looking at products/solutions etc as well as the _

### Attach screenshots.

![dropdowns](https://github.com/catppuccin/userstyles/assets/29279972/4cf83a25-5d10-47ad-a8e9-a197409ca4ab)
![searchbar](https://github.com/catppuccin/userstyles/assets/29279972/874a1cdc-aff3-4da6-81bd-c70661f6fcf4)
![underscore](https://github.com/catppuccin/userstyles/assets/29279972/6d376c2c-0dce-4338-800a-c0118d9cc572)

### What browser(s) are you seeing the problem on?

Firefox v119

### Any additional comments?

these only apply when logged out

**Comment by isabelroses** [comment]
Links to https://github.com/catppuccin/userstyles/issues/284, as they occur when logged out.

Thanks @GenShibe for the compilation of the issue.

**Comment by GenShibe** [comment]
<img width="577" alt="image" src="https://github.com/catppuccin/userstyles/assets/29279972/2b82da21-2515-45fe-83f5-26127e50cd35">oop forgot to add this hover to the issue as well
