### ISSUE TITLE
Various GitHub Projects elements aren't themed

### ISSUE THREAD

**Issue by Insprill** [catppuccin/userstyles#301]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

Various elements, and some entire views of GitHub project boards don't get themed.

### Attach screenshots.

![2023-11-09_00-43](https://github.com/catppuccin/userstyles/assets/52843537/14b5afb5-a4dd-4349-b2e4-dd457f9cbce6)
![2023-11-09_00-43_1](https://github.com/catppuccin/userstyles/assets/52843537/b5a761a0-2df5-4319-a2b7-2e45c4766c8a)
![2023-11-09_00-44](https://github.com/catppuccin/userstyles/assets/52843537/4a58c353-3c90-4155-9c39-1b57dc644bc0)
![2023-11-09_00-44_1](https://github.com/catppuccin/userstyles/assets/52843537/52f31b50-5841-445c-ac5b-ec0b63f5237e)
![2023-11-09_00-45](https://github.com/catppuccin/userstyles/assets/52843537/d46f7bf1-381b-4d60-a240-b7d0aed07900)

### What browser(s) are you seeing the problem on?

Firefox Developer Edition 120.0b8

**Comment by uncenter** [comment]
The latest PR linked above this comment closes this, from what I can tell. Please try it out and let me know.

![A screenshot of a project page for one of Catppuccin's projects](https://github.com/catppuccin/userstyles/assets/47499684/1e129c79-7bf1-4cdc-90f7-37ad4b532355)

**Comment by Insprill** [comment]
Yes, It looks like everything is properly themed now!

One slightly nitpicky thing I did notice, though, is on the roadmap view, when hovering over an issue, the border between it and the background disappears; the same with the border around the add buttons when not hovering.
![image](https://github.com/catppuccin/userstyles/assets/52843537/c5ca5599-c86c-4b83-bb95-e5ba1ea17071)
![image](https://github.com/catppuccin/userstyles/assets/52843537/c7663293-0e7a-445c-bc82-b4ee40c7df14)

**Comment by uncenter** [comment]
I'm not sure how to get to that view...

**Comment by Insprill** [comment]
![image](https://github.com/catppuccin/userstyles/assets/52843537/a4b228a2-1caa-4d2f-8434-b7282c6d1a84)

**Comment by uncenter** [comment]
Sweet thanks! I'll investigate later. I think I'll merge that PR for now and then I have another few changes in the works for various issues.
