### ISSUE TITLE
Tutanota renamed to "Tuta"

### ISSUE THREAD

**Issue by isabelincorp** [catppuccin/userstyles#319]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:tutanota

### Describe your problem.

Currently, the user style is broken without the new Tutanota URL added, which is "app.tuta.com"

### What browser(s) are you seeing the problem on?

Firefox v119.0

**Comment by isabelincorp** [comment]
I'll try to get to this issue soon, but I am raising the issue in the meantime.

**Comment by uncenter** [comment]
See: https://tuta.com/blog/tutanota-is-now-tuta
