### ISSUE TITLE
GitHub labels are unreadable

### ISSUE THREAD

**Issue by Insprill** [catppuccin/userstyles#352]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

Labels on Issues/Pull Requests are extremely bright, causing them to be completely unreadable.

### Attach screenshots.

|||
|-|-|
|![image](https://github.com/catppuccin/userstyles/assets/52843537/93d50c85-86da-45e7-9c3a-9b9872c66dbb)|![image](https://github.com/catppuccin/userstyles/assets/52843537/600b6991-5880-476a-b9cd-f137f9798d08)|
|![image](https://github.com/catppuccin/userstyles/assets/52843537/c49d9463-56d8-43fa-9bf8-9c28fc2a121e)|![image](https://github.com/catppuccin/userstyles/assets/52843537/d7f3b3d6-3a2b-4479-8a73-0b3ca49b38f8)|

### What browser(s) are you seeing the problem on?

Firefox Developer Edition 121.0b1

**Comment by alchzh** [comment]
Removing the rules for `.hx_IssueLabel` fixes this issue. They look pretty broken (no background opacity... etc.)
