### ISSUE TITLE
Add Duckduckgo to search engines

### ISSUE THREAD

**Issue by Dounial** [catppuccin/userstyles#411]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your problem.

I don't know why but there is a Searxng- as well as Google- etc. -theme to choose from but no Duckduckgo-theme. I use duckduckgo and would love to see my search engine added to the search engine-section.

### What browser(s) are you seeing the problem on?

Chromium

### Any additional comments?

Not my main request but I thought whoogle could also be added if someone takes the "challenge" already, but just a thought I had.

**Comment by soya-daizu** [comment]
Just fyi there's a non-userstyle implementation of catppuccin theme for Duckduckgo: https://github.com/catppuccin/duckduckgo

**Comment by isabelroses** [comment]
> Just fyi there's a non-userstyle implementation of catppuccin theme for Duckduckgo: https://github.com/catppuccin/duckduckgo However I find some minor unstyled elements and maybe things could be better handled if it was done with usertstyle

There's an open issue into the matter, I believe @rubyowo was working on it, this is probably a good place to check the progress, otherwise someone else could take over.

**Comment by GenShibe** [comment]
It's coming *very* soon :)
![mocha](https://github.com/catppuccin/userstyles/assets/29279972/82321fe9-aa00-4d74-9d03-b86108c7093c)

**Comment by sgoudham** [comment]
https://github.com/catppuccin/userstyles/tree/main/styles/duckduckgo
