### ISSUE TITLE
Numbers...

### ISSUE THREAD

**Issue by Lianaja32** [catppuccin/userstyles#480]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:ecosia

### Describe your problem.

When the light theme is active, the numbers are hard to see.

### Attach screenshots.

![Capture du 2024-01-28 18-23-28](https://github.com/catppuccin/userstyles/assets/79010647/80dc5c58-bcb0-4c84-837e-efba0612ac7b)

### What browser(s) are you seeing the problem on?

Firefox v122.0

**Comment by isabelroses** [comment]
Hello there, In my attempts to replicate the problem I did some search's such as the one below. Perhaps could you guide me to where the issue is?
![image](https://github.com/catppuccin/userstyles/assets/71222764/46c0043c-80f1-4499-b0cb-8e5f64ac1589)

**Comment by Lianaja32** [comment]
Go to https://www.ecosia.org/ with the catppucin stylus theme installed, it's when the light theme is selected in the settings that I have difficulty to see the number of tree planted.
As seen on the screenshot below.

![Capture du 2024-01-29 17-46-27](https://github.com/catppuccin/userstyles/assets/79010647/40ac5941-4962-4aca-876b-674d5e3744d8)
