### ISSUE TITLE
No hover over behavior for action buttons

### ISSUE THREAD

**Issue by simsrw73** [catppuccin/userstyles#489]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

I guess this could be a stylistic choice, but I like YT default themes use of hover over on the action buttons under the video (thumbs up/down, share, etc.) The themes here seem to have any hover over behavior defined for the action buttons. I prefer the feedback that it offers. Not sure if it was an intentional omission?

### What browser(s) are you seeing the problem on?

Version 1.62.153 Chromium: 121.0.6167.85 (Official Build) (64-bit)

**Comment by isabelroses** [comment]
Hello, thanks for pointing this out, I didn't even realise.
