### ISSUE TITLE
ChatGPT unthemed elements

### ISSUE THREAD

**Issue by Insprill** [catppuccin/userstyles#500]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:chatgpt

### Describe your problem.

Some elements recently became unthemed in the ChatGPT interface.

### Attach screenshots.
![image](https://github.com/catppuccin/userstyles/assets/52843537/1935a58b-909a-4e53-b844-730a87729bf4)

### What browser(s) are you seeing the problem on?

Firefox v122.0

**Comment by uncenter** [comment]
Thanks for making an issue. I'm working on a fix that you'll hopefully be able to get later today or tomorrow :)

**Comment by uncenter** [comment]
Sorry it's taking a bit but you can go to https://raw.githubusercontent.com/uncenter/ctp-userstyles/refactor/chatgpt-rewrite/styles/chatgpt/catppuccin.user.css and install the refactored version before it gets merged if you want to. Almost everything is there, just waiting on some new preview images and a few small unthemed things.

**Comment by Insprill** [comment]
Just installed that version, and it looks like most elements are properly themed now; although I did find one that isn't
![image](https://github.com/catppuccin/userstyles/assets/52843537/041bd8c5-2349-403f-bc76-7777305b910e)

I did notice, though, at least with the mocha variant, that the main background is using the mantle color. Shouldn't it be using base?

**Comment by uncenter** [comment]
> I just installed that version, and it looks like most elements are properly themed now, although I did find one that isn't ![image](https://private-user-images.githubusercontent.com/52843537/303943035-041bd8c5-2349-403f-bc76-7777305b910e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODA4MzEsIm5iZiI6MTcwNzY4MDUzMSwicGF0aCI6Ii81Mjg0MzUzNy8zMDM5NDMwMzUtMDQxYmQ4YzUtMjM0OS00MDNmLWJjNzYtNzc3NzMwNWI5MTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE5NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZGNlNGU3ZTE5YzhmMjE4MzM0YmI4MGVmM2I4NTFjNTExZjkzZWUyNjZhNDVmN2I1YTQ3MTMzZGVmMWMxOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vQ20z3s6Mh4aJO64YVW2PI4qJGM2TLAspMrBCMVLCwc)

Can you give me reproducible steps to access this?

> On the GPTs page, the featured GPTs are also a little harsh to look at, and there's not much contract between the cards and the text ![image](https://private-user-images.githubusercontent.com/52843537/303943300-ac533af0-0b99-4801-96e3-281988e1460e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2ODA4MzEsIm5iZiI6MTcwNzY4MDUzMSwicGF0aCI6Ii81Mjg0MzUzNy8zMDM5NDMzMDAtYWM1MzNhZjAtMGI5OS00ODAxLTk2ZTMtMjgxOTg4ZTE0NjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE5NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Y2IwNGUzZTRjYTlhZTE1ZWQ4NDU2OGUwYjliNmYwOWFmNDg3YzNkNWQ0YjVhOTBhOTk0ZjkyMGMzYjYyNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4cGLUwwEqgSELm94oVHe9TL1cFUyMdBlAXbNed7O91E)

Unfortunately I don't think I can access that page without paying from the premium version of ChatGPT...

> I also noticed that, at least with the mocha variant, the primary backgrounds use the mantle color. Shouldn't it be using base?

Fixed! Thanks for pointing it out.

**Comment by Insprill** [comment]
> Can you give me reproducible steps to access this?
You can reproduce it by downvoting any of its responses and submitting feedback (you don't have to enter/select anything)

**Comment by uncenter** [comment]
> > Can you give me reproducible steps to access this?
>
> You can reproduce it by downvoting any of its responses and submitting feedback (you don't have to enter/select anything)

Thanks! Should be fixed now, along with a couple other fixes for various borders and colors. Keep letting me know if you find any other issues please!
