### ISSUE TITLE
Google

### ISSUE THREAD

**Issue by GitMuslim** [catppuccin/userstyles#51]
### Link to repository

https://github.com/mustafakhalaf-git/google

### Screenshots

![image](https://user-images.githubusercontent.com/42213155/235514216-a45fe783-12c0-45a7-a044-8a916b9c4b4e.png)

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
hai @GitMuslim just noticed that a new issue has arrisen:
![image](https://github.com/catppuccin/userstyles/assets/71222764/beb7dba9-4b59-4168-a5ee-6f2ad4084477)

**Comment by GitMuslim** [comment]
this will need to be re-written in less first

**Comment by isabelroses** [comment]
> this will need to be re-written in less first

True, if u need help you can ask me, check the contrib docs or see the template.

**Comment by GitMuslim** [comment]
> > this will need to be re-written in less first
> 
> True, if u need help you can ask me, check the contrib docs or see the template in the root of this repo.

here it is https://github.com/catppuccin/userstyles/pull/325

**Comment by uncenter** [comment]
Probably should close it *when* the PR merges... lol.

**Comment by GitMuslim** [comment]
> Probably should close it _when_ the PR merges... lol.

This was just temporarily here until I make the less repo, no point of keeping it open anymore.
