### ISSUE TITLE
Youtube Black Bars unchanged

### ISSUE THREAD

**Issue by TabbyisTrans** [catppuccin/userstyles#518]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

Had downloaded the file with all the userstyles, my youtube previously had the black bars themed, but after re-installing the black bars are staying black, I have tried toggling black bars on and off to no avail.

### What browser(s) are you seeing the problem on?

Firefox 122.0.1

**Comment by uncenter** [comment]
Huh, seems to be working for me:

![Screenshot 2024-02-15 at 17 22 34 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/482ecac9-16ce-4fcb-a94a-86eff29ac2c1)

I'll try it with Firefox in a sec :)

**Comment by uncenter** [comment]
Working for me on `Firefox Developer Edition 123.0b9`:

https://github.com/catppuccin/userstyles/assets/47499684/eabf0357-bdb7-4ca9-89f0-30b70e0128f8

That is a different version than you have though. Try updating?

**Comment by TabbyisTrans** [comment]
![image](https://github.com/catppuccin/userstyles/assets/125671704/3efc3700-3114-41fd-8028-08922a4c65fa)

I'm on the most recent version of firefox I believe, heres what my config looks like

**Comment by uncenter** [comment]
You want "Enable black bars" *disabled* if you want them themed... what does it look like if you toggle it to disabled?

> I'm on the most recent version of firefox I believe, heres what my config looks like
Yeah I'm guessing its because I'm using Firefox Dev Edition. Shouldn't be a problem...

**Comment by TabbyisTrans** [comment]
![image](https://github.com/catppuccin/userstyles/assets/125671704/a08412e8-3b27-4882-9092-d440101ae067)

seems to look the same as with it on, not sure why it isnt working anymore, looks the same with other videos too

**Comment by TabbyisTrans** [comment]
All fixed now, had a conflicting extension

It appears that 'enhancer for youtube' ends up breaking the black bars even with custom appearences disabled, thank you for the help! :3

**Comment by uncenter** [comment]
Sweet! Glad you figured it out.
