### ISSUE TITLE
Latte issues with ChatGPT

### ISSUE THREAD

**Issue by nekowinston** [catppuccin/userstyles#526]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:chatgpt

### Describe your problem.

While shitposting on Discord I noticed these visual problems with the userstyle

### Attach screenshots.

![chat openai com_c_455af5a3-a62c-4797-a584-973256be7b12](https://github.com/catppuccin/userstyles/assets/79978224/a9196bd2-6564-498e-a9a8-00f5170adfcd)

### What browser(s) are you seeing the problem on?

Version 121.0.6167.184 (Official Build, ungoogled-chromium) (arm64)

### Any additional comments?

turn your lights on once in a while

**Comment by uncenter** [comment]
Are you fully up to date? Not seeing those issues present.

![Screenshot 2024-02-17 at 06 31 40 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/f9ad8772-32de-40ee-9e3f-08580e02dc93)
