### ISSUE TITLE
The userstyle for ChatGPT is too white?

### ISSUE THREAD

**Issue by jh-devv** [catppuccin/userstyles#537]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:chatgpt

### Describe your problem.

The userstyle for ChatGPT is too white? Shouldn't it be like that?

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/122896463/f627b8a3-8f18-47d3-9200-e85c3f127309)

### What browser(s) are you seeing the problem on?

Mozilla Firefox 122.0.1

**Comment by uncenter** [comment]
I'm aware of the issue, thanks.

**Comment by uncenter** [comment]
Should be closed in that. Let me know if there are further issues, also just feel free to adjust variables and make a PR!
