### ISSUE TITLE
Mail UI in external window in Gmail is not themed

### ISSUE THREAD

**Issue by searinminecraft** [catppuccin/userstyles#553]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:gmail

### Describe your problem.

On Gmail, when opening mail in an external window, the UI is not themed. Only some parts are themed but they're broken as heck

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/114207889/9671ebda-a030-4758-86a1-fc0ece66f353)
![image](https://github.com/catppuccin/userstyles/assets/114207889/4d90bf19-ae1a-4fec-bc6b-49e18f91496f)
![image](https://github.com/catppuccin/userstyles/assets/114207889/dcadc8e7-3ea0-4cde-a7e1-f6cbf9b209a9)

### What browser(s) are you seeing the problem on?

Chromium (ungoogled-chromium) 121.0.6167.184, Most likely all browsers are affected

**Comment by isabelroses** [comment]
So the main section of the email, is intentionally unthemed. But the rest I don't disagree.

**Comment by searinminecraft** [comment]
alright i changed the issue title and desc so its not confusing
