### ISSUE TITLE
AutoAO3App

### ISSUE THREAD

**Issue by enigmalea** [catppuccin/userstyles#56]
### Link to repository

https://github.com/enigmalea/autoao3app

### Screenshots

![image](https://user-images.githubusercontent.com/73132777/225091112-866b9f1b-aa81-4b25-8959-0ac304c3b28d.png)

### Any additional comments?

AutoAO3App is a scraper for [archiveofourown.org](https://www.ao3.org) which helps fans who are running or participating in fanworks gift exchanges to find, filter, and readd requests and view information on the exchange in an easier to read format than what's on available on AO3. It also adds an additional bookmarking feature.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by uncenter** [comment]
I'm going to close this issue for now but feel free to raise a PR adding your userstyle!
