### ISSUE TITLE
Rename libreddit to redlib

### ISSUE THREAD

**Issue by rubyowo** [catppuccin/userstyles#561]
### Is there an existing issue outlining your problem?

- [x] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

This *probably* should be a userstyle issue but what the hell.

libreddit is **dead**. It has been forked off into [redlib](https://github.com/redlib-org/redlib/).
So we should rename the userstyle accordingly

lbl:libreddit

**Comment by isabelroses** [comment]
Would it be better to lean into the fork or to have an array of names like anilist?
