### ISSUE TITLE
Pixlr

### ISSUE THREAD

**Issue by vanillyn** [catppuccin/userstyles#57]
### Link to repository

https://github.com/vanillyn/catppuccin-userstyles/tree/main/styles/Pixlr

### Link to app
e - https://pixlr.com/e/
x - https://pixlr.com/x/

### Screenshots

# pixlr e
![latte](https://user-images.githubusercontent.com/108785622/225450326-14d51c5b-884e-4df6-be71-28ca40e45ed6.png)
![frappe](https://user-images.githubusercontent.com/108785622/225450324-8751c5c3-2f8e-4903-855a-41582c47332d.png)
![macchiato](https://user-images.githubusercontent.com/108785622/225450329-3c14c9be-0fee-4041-8d4e-77c3e48b1a7f.png)
![mocha](https://user-images.githubusercontent.com/108785622/225450321-7c4867eb-95c0-4337-b211-50b4e59dfeee.png)

# pixlr x
![latte](https://user-images.githubusercontent.com/108785622/225450466-b48ddd27-3016-4f88-a16e-96a3b78c79d2.png)
![frappe](https://user-images.githubusercontent.com/108785622/225450485-b56832a7-41e5-4b43-b634-f9a7f1e49c20.png)
![macchiato](https://user-images.githubusercontent.com/108785622/225450497-4f5ea1dd-5c38-4804-8d80-b48f81126fea.png)
![mocha](https://user-images.githubusercontent.com/108785622/225450505-e69be922-85e6-4ec7-a37d-9042a84e74f2.png)

### Any additional comments?

This is a userstyle, and you may have to change the lightness in the app itself in order to have working text/icons

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by isabelroses** [comment]
Hello @vanillyn seeing as how these are the base domain/company would it be alright to compound them into one userstyle?

**Comment by vanillyn** [comment]
yeah - i should do that
more importantly, i am still currently using the stylus preprocessor, so i am going to have to port it to less first

**Comment by vanillyn** [comment]
Pixlr updated its UI, will need to change the theme (both to match the new ui and userstyles guidelines)
