### ISSUE TITLE
duckduckgo language switch should not be colored if disabled

### ISSUE THREAD

**Issue by atticus-sullivan** [catppuccin/userstyles#570]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:duckduckgo

### Describe your problem.

Duckduckgo has a switch right on top to select if the search results should be in a specific language. In the current version this switch is always colored in the accent color, no matter if it is disabled or enabled. This makes it hard to tell in which state the switch is.

#### With this userstyle:

![disabled](https://github.com/catppuccin/userstyles/assets/60581958/b822235f-159f-46f1-a812-004f3529f99a)
![enabled](https://github.com/catppuccin/userstyles/assets/60581958/fdaf85ce-b959-4ee2-8e37-83cec9bffb75)

#### In vanilla duckduckgo:

![disabled](https://github.com/catppuccin/userstyles/assets/60581958/f4581730-61ea-4bb5-8e73-8b2f9835a1e1)
![enabled](https://github.com/catppuccin/userstyles/assets/60581958/884a2b5c-9593-4a09-8b00-c93f42bb6071)

### What browser(s) are you seeing the problem on?

Firefox 122.0.1

### Any additional comments?

I'd propose to set the color to `surface0`.

(I'm also willing to work on this myself, but I don't have the time right now and maybe someone already acquainted with contributing here is faster than me)

**Comment by GenShibe** [comment]
i'll fix it *eventually* when i'm free

**Comment by atticus-sullivan** [comment]
Oh that was quick. Thank you.

There's just one issue with that fix (see your PR)
