### ISSUE TITLE
Hoppscotch.io

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/userstyles#63]
@justTOBBI has made a port for Hoppscotch.
It's ready for review: [justTOBBI/hoppscotch](https://github.com/justTOBBI/hoppscotch)

### Discussed in https://github.com/catppuccin/catppuccin/discussions/1907

<div type='discussions-op-text'>

<sup>Originally posted by **justTOBBI** February  4, 2023</sup>
### Will you make the port?

- [X] Yes, I'm willing to make the port

### How can the requested port be themed?

via Stylus Userthemes

### Has the requested port been themed already?

https://github.com/justTOBBI/hoppscotch

### Any additional comments?

Have a beautiful day, my friends ☕ </div>

**Comment by sgoudham** [comment]
Hey @justTOBBI, are you still planning on taking this forward and converting this to LESS?

**Comment by justTOBBI** [comment]
> Hey @justTOBBI, are you still planning on taking this forward and converting this to LESS? 

I am still planning on doing that, but it could take a while so someone could also jump in and help :)

**Comment by sgoudham** [comment]
Sounds good, @isabelroses might be interested then!

**Comment by isabelroses** [comment]
> Sounds good, @isabelroses might be interested then!

https://github.com/catppuccin/userstyles/issues/63#issuecomment-1685267815

**Comment by justTOBBI** [comment]
Tf how fast did you do that?

**Comment by sgoudham** [comment]
If @justTOBBI is happy with that, it'd be great to raise it as a pull request and get it merged here! @isabelroses

**Comment by justTOBBI** [comment]
I will do that very shortly after I finish working on my personal project

**Comment by isabelroses** [comment]
closed by https://github.com/catppuccin/userstyles/pull/212
