### ISSUE TITLE
Youtube Logo not there :<

### ISSUE THREAD

**Issue by sheplov11** [catppuccin/userstyles#632]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

Youtube logo not there! No matter if logo option is turned on or off.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/162576966/3b4edc48-f091-4a08-ada4-de104a83d54f)

### What browser(s) are you seeing the problem on?

Firefox 123.0

**Comment by isabelroses** [comment]
Theres a toggle for this, see:
![image](https://github.com/catppuccin/userstyles/assets/71222764/8f396661-d0b3-4df5-89df-0f514425d555)

**Comment by sheplov11** [comment]
![image](https://github.com/catppuccin/userstyles/assets/162576966/bb67baa3-0238-48c8-b493-e01d9ceeab19)
the thing is - it's on.

**Comment by isabelroses** [comment]
> ![image](https://private-user-images.githubusercontent.com/162576966/310862171-bb67baa3-0238-48c8-b493-e01d9ceeab19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MTE3ODcsIm5iZiI6MTcwOTgxMTQ4NywicGF0aCI6Ii8xNjI1NzY5NjYvMzEwODYyMTcxLWJiNjdiYWEzLTAyMzgtNDhjOC1iNDkzLWUwMWQ5Y2VlYWIxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QxMTM4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjBmY2NjMjkxZjEwOWViMmQ3NDljMDdjMDUxODhhNzMyMjc4NzQ4NjI0NGRiMDdhNjVmZTJlYjQ2YzIwZjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fXkh4NCg39lFZsKiFNdlsWdA_jkhY5IqMsurLiUVetg) the thing is - it's on.

Yeah the toggle is currently backwards it needs to be the opposite, ill PR quickly to fix this.

**Comment by sheplov11** [comment]
Right, it works now ;) Thanks. By the way, beautiful theme!
