### ISSUE TITLE
Reddit theme is broken

### ISSUE THREAD

**Issue by alba4k** [catppuccin/userstyles#637]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:reddit

### Describe your problem.

The box in the middle of the screen is grey after the last reddit ui update. 

### Attach screenshots.

![immagine](https://github.com/catppuccin/userstyles/assets/84153269/947ee154-1fd8-4c72-8812-62233e9abaea)

### What browser(s) are you seeing the problem on?

Mozilla Firefox 123.0.1

### Any additional comments?

The theme version is 2.0.8 (aka latest)

**Comment by No0ne003** [comment]
how do you set the theme on any website, please answer

**Comment by isabelroses** [comment]
> how do you set the theme on any website, please answer

Please can you elaborate?

**Comment by alba4k** [comment]
> how do you set the theme on any website, please answer

install the stylus browser extension, and click the install button on the readme

**Comment by No0ne003** [comment]
thanks man i doesn't know about the extanstion
