### ISSUE TITLE
Twitch: Event notifications like Hypetrains become unreadable

### ISSUE THREAD

**Issue by Gambloide** [catppuccin/userstyles#649]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:twitch

### Describe your problem.

Event notifications like Hypetrains become unreadable.

Vanilla:
![Screenshot_20240310_160925](https://github.com/catppuccin/userstyles/assets/5939852/d23b98d6-58ef-4b3a-b1a4-dd802ad6bc87)

With latest Catppuccin style:
![Screenshot_20240310_160903](https://github.com/catppuccin/userstyles/assets/5939852/0f59f255-9076-4a52-9947-cd57ffffd70c)

The stylesheet attempts to mix a very dark with a very light background but not accounting for that with the text colors. Just statically changing the text color will not fix this, as the background changes dynamically based on event progress.

Maybe using the accent color for the pill in the top and and using an overlay or surface color from the palette would be a better choice here.

### What browser(s) are you seeing the problem on?

LibreWolf 123.0-1

**Comment by Gambloide** [comment]
I just pulled the update (1.2.0). If the background color really has to be retained, wouldn't it make sense to at least give the text some shadow to make it legible? 🤔

![Screenshot_20240325_160536](https://github.com/catppuccin/userstyles/assets/5939852/16a15c42-ae45-4b80-ad98-eaec36d39420)

**Comment by isabelroses** [comment]
We could, make the fade out the bg, that might help.
