### ISSUE TITLE
Wikipedia equations

### ISSUE THREAD

**Issue by razimantv** [catppuccin/userstyles#660]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:wikipedia

### Describe your problem.

Equations show up in black in dark themes, making it hard to see them. I don't know much about CSS theming, but this might be unfixable because Wikipedia is rendering the equations as images. In that case, it might help to put them on a light background.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/3823215/8deb1423-8c2c-4a6e-87d0-f995fc11f37d)

### What browser(s) are you seeing the problem on?

Firefox v123.0.1

**Comment by iliqKichev** [comment]
The top Wikipedia dart theme uses this to make the equations work:

```
.mwe-math-fallback-image-inline img,
    .mwe-math-element img,
    img[src*="LaTeX"] {
        filter: invert(100%);
    }
```

I just added it to the theme and it worked, but I haven't tested it heavily.

**Comment by isabelroses** [comment]
> The top Wikipedia dart theme uses this to make the equations work:
> 
> ```
> .mwe-math-fallback-image-inline img,
>     .mwe-math-element img,
>     img[src*="LaTeX"] {
>         filter: invert(100%);
>     }
> ```
> 
> I just added it to the theme and it worked, but I haven't tested it heavily.

This would work, we would need to include a `when not (@lookup = latte)` just to make sure that the theming only applies on the dark themes.
