### ISSUE TITLE
Unthemed Wikipedia elements

### ISSUE THREAD

**Issue by enderprism** [catppuccin/userstyles#670]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:wikipedia

### Describe your problem.

Some elements of Wikiepedia pages aren't themed and stay white, notably banners, which makes them unreadable.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/76617157/2a1164c2-1d0a-4601-b837-ae0c3f83ac19)

### What browser(s) are you seeing the problem on?

Firefox v123.0.1

**Comment by kingofcube** [comment]
I can fix it.

**Comment by kingofcube** [comment]
Yeah, still waiting for it to be themed

**Comment by GitMuslim** [comment]
@enderprism can you provide the link for the page?

**Comment by enderprism** [comment]
https://fr.wikipedia.org/wiki/AAA_%28jeu_vid%C3%A9o%2

**Comment by lplawlor** [comment]
As a follow up, it seems that the box which appears when no article exists at that link is completely different depending on the language.

In English ([example](https://en.wikipedia.org/wiki/Name_of_Fake_Article)), the structure goes:
```html
<div class="noarticletext">
  <div class="mw-parser-output">
    <style>...</style>
    <table id="noarticletext" class="plainlinks fmbox fmbox-system">
      ...
```
And so the `background-color` styling is already done by the [existing CSS for `.mw-parser-output .fmbox`](https://github.com/catppuccin/userstyles/blob/2bb7df4ce7e03d192cd85433fa82dc3a763fd313/styles/wikipedia/catppuccin.user.css#L174-L177).

In French ([example](https://fr.wikipedia.org/wiki/Name_of_Fake_Article)), the structure is entirely different, and again for Spanish, German, etc. Moreover, some of the elements within these boxes supply their own `style` directly within the HTML, so we need to override them with `!important`.

With all that said, the following seems to fix things on all the languages I've tried, (though I haven't done exhaustive testing):

```css
    .noarticletext, #noarticletext {
      background-color: @base !important;
    }
    
    #sisterproject {
      background-color: @mantle !important; 
    }
```

English (en.wikipedia.org):
![image](https://github.com/catppuccin/userstyles/assets/60618151/83dfdbe5-38ca-4258-b105-834a2c07e1e4)

French (fr.wikipedia.org):
![image](https://github.com/catppuccin/userstyles/assets/60618151/85732d6f-599d-48b8-9d59-2d26469daeba)

Spanish (es.wikipedia.org):
![image](https://github.com/catppuccin/userstyles/assets/60618151/08b1a8f0-dd0d-4324-8c39-6f3cc40658b5)

Ukrainian (uk.wikipedia.org):
![image](https://github.com/catppuccin/userstyles/assets/60618151/5785160e-6ac9-485d-baa2-d289ba84a763)
