### ISSUE TITLE
youtube: transparent header bar not themed when logged in

### ISSUE THREAD

**Issue by BPplays** [catppuccin/userstyles#677]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

the header bar on youtube is not themed when im logged in
when signed out youtube doesn't seem to have a transparent header bar

ive also replicated on firefox 125.0a1 with only ublock origin disabled for youtube, dark reader disabled, and stylus installed

### Attach screenshots.

![header bar](https://raw.githubusercontent.com/BPplays/images/main/catppuccin_userstyles/ytheadernthmd/Screenshot%202024-03-15%20123200.png)

### What browser(s) are you seeing the problem on?

124.0.6358.0 (Official Build) canary (64-bit) (cohort: Clang-64)

**Comment by isabelroses** [comment]
This is potentially related to ambient mode.

**Comment by BPplays** [comment]
i seems to still happen and also it happens on the home page, but i think i got it fixed i'll make a pr
