### ISSUE TITLE
GitHub repository topic remove button is offset

### ISSUE THREAD

**Issue by Insprill** [catppuccin/userstyles#686]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

When editing topics for a repo, the X button to remove a topic is offset into the corner of the highlighted area.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/52843537/73f7ce89-86c2-4d5d-8cad-710ba29f5e1d)

### What browser(s) are you seeing the problem on?

Firefox 123.0.1

**Comment by uncenter** [comment]
This is an issue with GitHub itself, not the userstyle:
![image](https://github.com/catppuccin/userstyles/assets/47499684/12a81d76-ffef-40cd-ab44-edfeabd4e0f7)
