### ISSUE TITLE
Bluesky: various unthemed elements

### ISSUE THREAD

**Issue by ThatOneUnoriginal** [catppuccin/userstyles#700]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:bsky

### Describe your problem.

Multiple sections of the Bluesky Catppuccin theme are not correctly themed. They're showing the default Bluesky colors instead of the Catppuccin colors. The screenshots bellow only show a selection of instances of elements not being correctly colored but they litter the entire theme currently.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/70731807/1cca6fc7-02fc-4b6a-84a7-0d0bc48348b9)
![image](https://github.com/catppuccin/userstyles/assets/70731807/1e438e6a-7bd4-45e6-a1e6-9802490f7b3a)

### What browser(s) are you seeing the problem on?

Vivaldi: 6.6.3271.53 (Stable channel) (64-bit)

**Comment by fmauNeko** [comment]
Hello!

If you switch the Dark Theme setting from "Dim" to "Dark", it fixes almost everything.

**Comment by ThatOneUnoriginal** [comment]
> Hello!
> 
> If you switch the Dark Theme setting from "Dim" to "Dark", it fixes almost everything.

Changing the Dark Theme setting to dark worked. Though I should note that maybe this should be noted on the GitHub page for the BlueSky Catppuccin theme in a "usage" section? Will close the issue though since that's more a request then an issue.
