### ISSUE TITLE
Brave Search is no longer themed

### ISSUE THREAD

**Issue by Insprill** [catppuccin/userstyles#713]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:brave-search

### Describe your problem.

Brave Search is no longer themed at all.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/52843537/88ff0df6-6634-4434-8891-3535669a884e)

### What browser(s) are you seeing the problem on?

Firefox v124.0.1

**Comment by nonetrix** [comment]
Could accent color also be added as well since you are rewriting it? I never really liked the Brave Search theme for some reason always
