### ISSUE TITLE
Bluesky: various unthemed elements

### ISSUE THREAD

**Issue by ThatOneUnoriginal** [catppuccin/userstyles#722]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:bsky

### Describe your problem.

Here a list of issues I found with the BlueSky Catppuccin theme (using the correct "Dark" theme option on Bluesky)

1. In the notifications section the new notification background is not correctly themed using the default colour for it. Not to mention the section that is themed (the inner part) follow the colour scheme for read notifications instead of unread/new notifications. 

2. Any instance where a small confirmation popup like when sharing/copying links to profiles/posts or when following/unfollowing someone it doesn't look right. Either the background color or text color would need to be changed to make it more legible (or both.)

3. When viewing an image, if the image has an attached alt text to it, said text is nearly impossible to read due to low legibility. This also applies within the text on the "ALT" icon but impacts user experience more when trying to read said text.

### Attach screenshots.

1. 
![image](https://github.com/catppuccin/userstyles/assets/70731807/2187b652-510f-4f3c-9ac3-b5581393cb27)

2.
![image](https://github.com/catppuccin/userstyles/assets/70731807/e1b2d4a6-f884-437a-bba3-621aa52a81ef)

3. 
![image](https://github.com/catppuccin/userstyles/assets/70731807/d92295e2-79c0-4e7e-8d41-a15b03cff7e4)
![image](https://github.com/catppuccin/userstyles/assets/70731807/95d8afab-2cbc-4964-920e-b73133ddf49e)

### What browser(s) are you seeing the problem on?

Vivaldi: 6.6.3271.53 (Stable channel) (64-bit) 

### Any additional comments?

Most of these issues (except for the first) don't appear on the light theme so just keep that in mind.

**Comment by RoootTheFox** [comment]
maintainer of the bsky theme here - sorry for being inactive, i was busy with a lot of other stuff and haven't had the time or motivation to work on the theme - im currently updating the theme for bluesky's changes, i'll report back once its fixed ^^

**Comment by RoootTheFox** [comment]
whoops, completely forgot about this issue - as of #1389 these issues should be fixed now ^^
