### ISSUE TITLE
Wikipedia: Poor text contrast in custom-colored tables

### ISSUE THREAD

**Issue by bustinbung** [catppuccin/userstyles#742]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:wikipedia

### Describe your problem.

In some custom-styled tables, text contrast is unreadably low. I'm unsure if this can be fixed by way of the userstyle or if it's something that needs to be handled elsewhere.

Example: [Bluecoats Drum and Bugle Corps](https://en.wikipedia.org/wiki/Bluecoats_Drum_and_Bugle_Corps#Show_summary_(1974%E2%80%932023))
Under "Show Summary":
| Background color | Text color | Contrast (as reported by dev tools) |
|------------------|------------|-------------------------------------|
| #d0f0c0          | #cdd6f4    | 1.16                                |
| #add8e6          | #cdd6f4    | 1.05                                |
| #d4af37          | #cdd6f4    | 1.45                                |

### Attach screenshots.

<img width="393" alt="image" src="https://github.com/catppuccin/userstyles/assets/22670587/68eaba8c-c61a-4d6f-b0b4-138903d1ecb1">

### What browser(s) are you seeing the problem on?

Arc for MacOS 1.36.0

**Comment by isabelroses** [comment]
closed by https://github.com/catppuccin/userstyles/pull/743
