### ISSUE TITLE
nixos.wiki is now wiki.nixos.org

### ISSUE THREAD

**Issue by isabelroses** [catppuccin/userstyles#781]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:nixos.wiki

### Describe your problem.

https://nixos.wiki is being replaced by https://wiki.nixos.org, both of these websites use mediawiki but somewhat different css.

### What browser(s) are you seeing the problem on?

N/A

**Comment by somerand0mcat** [comment]
i think #1120 will close this issue

**Comment by orxngc** [comment]
Going to attempt to do this now.
