### ISSUE TITLE
automate all userstyle install

### ISSUE THREAD

**Issue by trinkey** [catppuccin/userstyles#791]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

the current install all userstyles in the [releases tab](https://github.com/catppuccin/userstyles/releases/) and on [uncenter's website](https://ctp-aui.uncenter.dev) are both extremely outdated. this could possibly be automated with a github action or whatever for either on commit to main or just timer based

**Comment by isabelroses** [comment]
The tag is outdated, but we upload the import using `gh release import --clobber` so we replace the `import.json` with a new copy each time the build workflow runs.

**Comment by uncenter** [comment]
And the import file on my website is updated every hour? What are you talking about xD

![Screenshot 2024-04-09 at 16 28 50 (Arc)](https://github.com/catppuccin/userstyles/assets/47499684/16541412-c65e-4091-b49f-1ff5ae9a5ab7)
