### ISSUE TITLE
github catppuccin not working

### ISSUE THREAD

**Issue by kaushiksahu18** [catppuccin/userstyles#796]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:github

### Describe your problem.

not working, showing error text on top-left!

### Attach screenshots.

![Screenshot from 2024-04-10 13-44-13](https://github.com/catppuccin/userstyles/assets/113049724/ebb498ff-cdea-4463-a795-fe3173000863)

### What browser(s) are you seeing the problem on?

brave browser (brave-bin 1:1.64.116-1)

**Comment by isabelroses** [comment]
The warning in the top left, says that you need to go to *Settings* then *Appearance* and select either the default light or dark themes.
