### ISSUE TITLE
Stylus live reload text isn't themed

### ISSUE THREAD

**Issue by trinkey** [catppuccin/userstyles#813]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:stylus

### Describe your problem.

The live reload text (`#live-reload-install-hint`) is darkcyan instead of like `@subtext0` or something

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/97406176/a903eed0-a989-4c80-92bf-4bc02367eb77)

### What browser(s) are you seeing the problem on?

Firefox v124.0.2

**Comment by uncenter** [comment]
Feel free to submit a PR. I'd go for `@teal` here to match what they have going.

**Comment by trinkey** [comment]
ill get around to it (i'm gonna forget within 20 minutes)
