### ISSUE TITLE
pinterest userstyle issue when applying

### ISSUE THREAD

**Issue by kaushiksahu18** [catppuccin/userstyles#824]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:pinterest

### Describe your problem.

in stylus i was trying to save this userstyle ans error occure
***
> error: 
Please change the value of @name or @namespace to avoid overwriting an existing style.
***

### Attach screenshots.

![Screenshot from 2024-04-18 11-35-38](https://github.com/catppuccin/userstyles/assets/113049724/e6bbd855-eef3-47dd-8e11-b06eea52f580)

### What browser(s) are you seeing the problem on?

brave browser

**Comment by isabelroses** [comment]
This means that you have another userstyle with the same metadata properties `@name` and `@namesapce` to fix this find and delete the duplicate userstyle and then install the pinstrest userstyle.
