### ISSUE TITLE
youtube: readability issues in shorts player

### ISSUE THREAD

**Issue by aemogie** [catppuccin/userstyles#827]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

In the shorts player, the like, comment and share buttons probably need to use a background gradient the same way the video title does.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/54412618/52f26df1-3ea1-45d1-82f8-53e166504045)

### What browser(s) are you seeing the problem on?

Firefox v124.0b5 (Developer Edition)

### Any additional comments?

This issue exists in the official style as well, not just the catppuccin one so we could wait for a fix to land there.

**Comment by isabelroses** [comment]
the biggest issue with shorts is that no matter what colour we set the text to it's always almost invisible. if we make it dark you can't read it on dark videos, and vice versa for light ones. This is almost unfixable and YouTube themselves don't care that much since they have the same issue.
