### ISSUE TITLE
Spotify: Text shows in white on white when using Latte theme

### ISSUE THREAD

**Issue by bustinbung** [catppuccin/userstyles#831]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:spotify-web

### Describe your problem.

Track title names show up as white on off-white, making them incredibly hard to read.

### Attach screenshots.

<img width="931" alt="image" src="https://github.com/catppuccin/userstyles/assets/22670587/9b854aa1-60f7-471d-b309-876f3a15fcf9">

### What browser(s) are you seeing the problem on?

Arc v1.38

### Any additional comments?

Using the Latte theme.

**Comment by Tnixc** [comment]
Fixed in #879

**Comment by weightedangelcube** [comment]
This issue has appeared again: 
<img width="1858" height="803" alt="Image" src="https://github.com/user-attachments/assets/7f228044-230a-41a1-a3a9-476391070b8d" />

Also happens on the lyrics pages:
<img width="1852" height="802" alt="Image" src="https://github.com/user-attachments/assets/78ace419-6ffc-4904-b5f2-d15222685137" />
