### ISSUE TITLE
shouldn't we be using a .less file extension for files using Less as the pre-processor instead of using .css?

### ISSUE THREAD

**Issue by BPplays** [catppuccin/userstyles#856]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe your issue.

using .css seems to confuse vscode until you manually change to Less and it probably does the same for other editors too

**Comment by isabelroses** [comment]
I wish this was possible but as https://github.com/openstyles/stylus/wiki/Usercss#contents lays out the only allowed file extension for userstyles is .user.css

**Comment by uncenter** [comment]
Also uhhh there shouldn't be any confusion at all or manual set up by you in VSCode. The repository has the association configured for you: https://github.com/catppuccin/userstyles/blob/76f6bd8c44044afc087b3ad0b5acd90560b1a901/.vscode/settings.json#L3.

**Comment by BPplays** [comment]
ahh, that makes sense, i was just opening the folder with the style in it in vscode
