### ISSUE TITLE
gmail: Assumption of a base dark-mode theme

### ISSUE THREAD

**Issue by Fenrirthviti** [catppuccin/userstyles#870]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:gmail

### Describe your problem.

Currently, the gmail theme makes an assumption (requirement?) that a base "dark mode" theme is already selected, which means certain elements will not display properly if the base gmail theme is light. There are specific situations where you *cannot* apply a dark mode theme to a gmail inbox (such as a delegated inbox, or some enterprise environments) and it would be nice if things worked regardless of the base theme selected. I realize this is annoying as some of the things that do not display properly are images, but I hear tell of dark CSS magic to get them to display properly. Bit of an edge case for sure, but figured I would report as maybe someone a bit more knowledgeable than myself would be able to fix it up quick enough.

Examples below do not cover all instances of this, but if it's helpful, I can try to provide screenshots of things as I come across them.  Most are fairly obvious when you have a light mode theme selected. #864 just recently merged fixed a few of these I had noticed and had local patches for, but wanted to raise the larger concern for tracking either way.

Thanks to everyone for all their hard work, and let me know if any additional information is helpful!

### Attach screenshots.

**Example when a Dark Mode theme is selected as base:**
Section titles:
![image](https://github.com/catppuccin/userstyles/assets/6519624/7bbe2f19-eed6-4e67-97d0-7660215fb1f9)

Attachment icon:
![image](https://github.com/catppuccin/userstyles/assets/6519624/d79e2cbf-b02b-46be-b523-5865c033b621)

**Example when a Light Mode theme is selected as a base:**
Section titles:
![image](https://github.com/catppuccin/userstyles/assets/6519624/6620f747-ec23-470e-ad88-bb5e47cff88d)

Attachment icon:
![image](https://github.com/catppuccin/userstyles/assets/6519624/a0f71943-6ca9-495a-af82-3274c3d34835)

### What browser(s) are you seeing the problem on?

Chrome 124.0.6367.63

**Comment by uncenter** [comment]
Added a note to suggest using the default dark theme in #921.

> There are specific situations where you cannot apply a dark mode theme to a gmail inbox (such as a delegated inbox, or some enterprise environments) and it would be nice if things worked regardless of the base theme selected.

Unfortunately the CSS selectors change between these themes due to how poorly it is implemented in Gmail, and supporting additional themes is too difficult on top of what we already have. At some point we could look into using the default light theme as base, but I've just rewritten the entire theme based on the dark theme and I don't want to spend more time refactoring it again 😅

**Comment by Fenrirthviti** [comment]
Fair enough, I suspected that might be the case when I was modifying things on my end to fix the major issues. I'll just keep my local, if extremely hacky, changes which are working well enough.
