### ISSUE TITLE
Weird white panels in the Arch wiki

### ISSUE THREAD

**Issue by LeonN534** [catppuccin/userstyles#896]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:arch-wiki

### Describe your problem.

There are bad looking white panels in some parts of the UI. The fixed navbar is the most noticeable since it appears in all sub pages of the wiki.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/77511070/4f86c270-51e5-4552-9f80-098677e994b2)
![image](https://github.com/catppuccin/userstyles/assets/77511070/e621a32e-51dc-4fb5-a6d6-013a2bb7daee)

### What browser(s) are you seeing the problem on?

Firefox v126.0

**Comment by seamuseats** [comment]
I would like to add that I am having the same issue on waterfox. I unfortunately have to disable the style until this is fixed.
