### ISSUE TITLE
Feature request: Separate `lightAccent` and `darkAccent` colors

### ISSUE THREAD

**Issue by tmprnc** [catppuccin/userstyles#900]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

All.

### Describe your problem.

I have Twitter switch from light to dark theme based on Windows theme, which switches based on sunrise/sunset.
I love the green accent color on the dark palettes, because it's a beautiful pastel green. I do not like the dark saturated green of the Latte palette I use during daytime, though. I would like to be able to set Catppuccin for Twitter to use Latte + Flamingo during the day and Mocha + Green during the night. I'm sure there's a hacky way I could do this, such as changing the actual hex values in the lookup table, but I feel like that would be a rather unclean way to do this, and modifying the CSS myself would result in either them being broken every update, or conversely, depriving me of updates. I'm not familiar at all with CSS pre-processors, so my attempts to try and figure out how to change it more cleanly failed.

### What browser(s) are you seeing the problem on?

Vivaldi 6.7.3329.31 (Stable channel) (64-bit)

**Comment by isabelroses** [comment]
The largest issue with twitter, is that the webpage is full of inline styling. This makes it take a significant amount of time to create and maintain, adding a light mode would be nice but a very strenuous task.

**Comment by tmprnc** [comment]
> The largest issue with twitter, is that the webpage is full of inline styling. This makes it take a significant amount of time to create and maintain, adding a light mode would be nice but a very strenuous task.

I don't understand. Catppuccin for Twitter _already has_ a working "dark/light" mode switch going on. It just ignores Twitter's own theme choices and simply asks you to run blue color + pure black Twitter, then rewrites the colors. Effectively, this is white theme being written over AMOLED black.

https://github.com/catppuccin/userstyles/assets/3785923/c253b23f-4a69-4954-ab62-62f54926d6f6

What I'm asking is not about that. That _already works_. What I'm asking is to have separate accent colors (i.e. Rosewater for Latte WHEN the "light mode" toggle is on, and Green for Mocha when the "dark mode" toggle is on). I think if it is possible to completely change the entire theme on the fly based on system's light/dark mode setting, then it should be able to do so with the accent color also, right?

**Comment by isabelroses** [comment]
Ahh, I understood it as a dark/light switcher and since the first thing I saw when moving to light mode was this
![image](https://github.com/catppuccin/userstyles/assets/71222764/ea271c26-3eb2-4133-8fba-4864cac45c71)

But it should be possible to do this. Curious whether its worth the effort though. I'd like to hear @uncenter views.

**Comment by tmprnc** [comment]
I should mention that I incorrectly believed I was using the latest version of the userstyle. Since I tried to make changes to it, it disabled automatic updates, most likely. The newest version doesn't have the feature I'm requesting either, but I should have checked before I hit the tickbox.

**Comment by uncenter** [comment]
> Ahh, I understood it as a dark/light switcher and since the first thing I saw when moving to light mode was this ![image](https://private-user-images.githubusercontent.com/71222764/331862550-ea271c26-3eb2-4133-8fba-4864cac45c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjY0MjIsIm5iZiI6MTcxNjEyNjEyMiwicGF0aCI6Ii83MTIyMjc2NC8zMzE4NjI1NTAtZWEyNzFjMjYtM2ViMi00MTMzLThmYmEtNDg2NGNhYzQ1YzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEzNDIwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOTMwOTQzNDg5ZjY1ODkwZTlkOTliZTBlMTE1ZTIwODk5MTk3NzJkMWUzZGMwZWY5MDgzZmU1YTg3NTI4NWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hAgEeC3nvOiNkytbWNVPrHFIjt0zUys2bDqVeR2MRZw)
> 
> But it should be possible to do this. Curious whether its worth the effort though. I'd like to hear @uncenter views.

I mean it is a lot more work for both updating all 80-something userstyles and just more confusing options for users to pick from. Seeing as you are the first person to request this, maybe we leave this open for a little while and see if others also want this?

**Comment by trinkey** [comment]
I +2 this feature request, and it shouldn't be difficult at all to do:
![image](https://github.com/user-attachments/assets/00be5918-5ef6-431e-9842-7dac15fbd661)

**Comment by uncenter** [comment]
@trinkey it's pretty clearly not about the difficulty, as we know we already have dark and light flavor options. The question is how often will people use this? If 10/1000 people want to use this, the other 990 have to then change two dropdowns just to change their accent color if they want it the same for both. How much additionally complexity are we wanting to introduce? Making this change happen is difficult with over a hundred userstyles now. This will also break existing setups and we can't easily migrate users.

**Comment by uncenter** [comment]
I'm going to close this as not planned for now, though I don't think including this in the docs would be wise either; the usage instructions are already pretty complicated and I don't want to add more confusion/complexity, let alone how annoying it would be to change this across all the userstyles you use 😃
