### ISSUE TITLE
unstyled inline styles

### ISSUE THREAD

**Issue by trinkey** [catppuccin/userstyles#904]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:chatgpt

### Describe your problem.

Sometimes chatgpt decides to do some thing that makes there be inline styles and those inline styles arent the correct color

fix:
```css
[style*="color: rgb(204, 0, 0)"] {
  color: @red;
}
```

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/97406176/eb276d4e-e0ff-400a-87be-f51d0326af00)

![image](https://github.com/catppuccin/userstyles/assets/97406176/5acff3ab-1246-4f75-b1ed-ba42fe79e467)

### What browser(s) are you seeing the problem on?

firefox stable latest

**Comment by uncenter** [comment]
In the future why not just make a PR when you have a fix? Not sure why this needs to be an issue...

**Comment by isabelroses** [comment]
> In the future why not just make a PR when you have a fix? Not sure why this needs to be an issue...

Do both, create an issue to let it be know that it exists and to notify others that your going to fix it.

**Comment by uncenter** [comment]
> > In the future why not just make a PR when you have a fix? Not sure why this needs to be an issue...
> 
> Do both, create an issue to let it be know that it exists and to notify others that your going to fix it.

If it is a 3 line fix that makes sense to merge it has no reason to be an issue in the first place. It'll get merged faster than I can read the issue template lol
