### ISSUE TITLE
Mobile support?

### ISSUE THREAD

**Issue by Void48** [catppuccin/userstyles#92]
Would it be possible to have this theme support mobile devices? I tried injecting the css but it doesn't work

lbl:github

**Comment by SpomJ** [comment]
pretty sure kiwi supports chrome extensions

**Comment by NameLessGO** [comment]
Firefox* supports extensions

*Beta and Nightly, the extensions should be coming to stable FF soon

https://blog.mozilla.org/addons/2023/09/27/test-firefox-android-extensions-and-help-developers-prepare-for-an-open-mobile-ecosystem-in-december/

https://old.lemmy.sdf.org/post/7022029

**Comment by isabelroses** [comment]
Just wanted to note, we have since had some PR's improving the mobile usage:

- https://github.com/catppuccin/userstyles/pull/173
- https://github.com/catppuccin/userstyles/pull/171
- And some of my own various PRs

**Comment by uncenter** [comment]
I think this can be closed... there shouldn't be any remaining issues with the GitHub userstyle on desktop and that should be the same for mobile.

**Comment by isabelroses** [comment]
> I think this can be closed... there aren't be any remaining issues with the GitHub userstyle (*while logged in) on desktop and that should be the same for mobile.

I'll play around with this one a bit more before closing this issue, hopefully all is good.

**Comment by isabelroses** [comment]
From what I can tell we seem to have good feature parity between mobile and desktop versions.
