### ISSUE TITLE
New (beta) github file view is slightly broken

### ISSUE THREAD

**Issue by ozwaldorf** [catppuccin/userstyles#93]
![image](https://user-images.githubusercontent.com/8976745/221421823-f05a7b35-3371-46a3-855b-5fa2fb513d8d.png)

lbl:github

**Comment by mokrinsky** [comment]
![image](https://github.com/catppuccin/userstyles/assets/463907/f9e3dcb0-18a1-4a6f-999d-b61bba0a2995)
on light default github theme it's even worse :)

**Comment by isabelroses** [comment]
> on light default github theme it's even worse :)

If your getting your images like that please (and your on mocha) please change the github theme itself to a dark mode based theme, it will help at least a small amount
