### ISSUE TITLE
drive: unstyled svgs

### ISSUE THREAD

**Issue by trinkey** [catppuccin/userstyles#930]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:google-drive

### Describe your problem.

The icons on the upload panel are unstyled

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/97406176/6441069a-4b2a-4d93-a54d-1b582ef9fc8d)

### What browser(s) are you seeing the problem on?

firefox stable latest

**Comment by GenShibe** [comment]
<img width="402" alt="image" src="https://github.com/catppuccin/userstyles/assets/29279972/818fffef-3923-46f9-9fbe-49a670ef33f3">

it seems like that the icons on the left are *not* svgs, rather PNGs, but the green checkmark *is* an svg

**Comment by trinkey** [comment]
great consistency skills from google
