### ISSUE TITLE
Like icon become transparent when the video is liked

### ISSUE THREAD

**Issue by IvanKarpov-1** [catppuccin/userstyles#946]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:youtube

### Describe your problem.

As I said in the title, the like icon becomes transparent when I like the video. With the dislike icon that's not happening. I use the Macchiato flavor with the Teal accent color.

### Attach screenshots.

No reactions:
![image](https://github.com/catppuccin/userstyles/assets/75908576/0bcf0cce-0cf9-493f-83ca-586019f62b78)
Liked:
![image](https://github.com/catppuccin/userstyles/assets/75908576/ac529216-b87c-4bdc-9396-1c214fe012cb)
Disliked:
![image](https://github.com/catppuccin/userstyles/assets/75908576/142ce56f-eb6c-4b21-b30f-9325a5ee09c6)

### What browser(s) are you seeing the problem on?

Google Chrome 125.0.6422.141

**Comment by isabelroses** [comment]
Seems to be a regression from youtube themselves, see below unthemed image. So theres not much we can actually do here. Thanks for the issue report though, it was very detailed.
![image](https://github.com/catppuccin/userstyles/assets/71222764/a897f585-a88a-47ab-a28f-9b0f500c099a)
