### ISSUE TITLE
google: unstyled widgets

### ISSUE THREAD

**Issue by trinkey** [catppuccin/userstyles#960]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:google

### Describe your problem.

Many of the widgets that come up when searching for specific things are unstyled or only partly styled

### Attach screenshots.

stopwatch: the border is unstyled, along with the icons. also when going into fullscreen, the background isn't styled either

![image](https://github.com/catppuccin/userstyles/assets/97406176/902ea445-f4f3-4688-9beb-306e1839df77)

periodic table

![image](https://github.com/catppuccin/userstyles/assets/97406176/b7ddadd4-955a-4d88-9969-40cec03e7c6b)

roll a die/flip a coin: the icons and main section are unstyled. the main section uses canvas although other parts can still be styled

![image](https://github.com/catppuccin/userstyles/assets/97406176/75f013d2-ca6c-4a43-a4e5-447e57e2084c)

games: the play button is unstyled

![image](https://github.com/catppuccin/userstyles/assets/97406176/69f95d9f-368a-4a54-b4ac-cd57c747a0f4)

answer highlighting: background should be set to `none` to remove the default linear gradient

![image](https://github.com/catppuccin/userstyles/assets/97406176/6d5a4255-0272-46ca-802d-8bea0a750c36)

"things to know" section

![image](https://github.com/catppuccin/userstyles/assets/97406176/79ef7cfc-e009-4206-8f55-27b91089c182)

"More" button

![image](https://github.com/catppuccin/userstyles/assets/97406176/6ac3dbaf-ca35-4051-9e65-4fffd2e34c3f)

shopping: most unique areas are unstyled

![image](https://github.com/catppuccin/userstyles/assets/97406176/90fffd0d-4ecb-4014-86e3-78a62ae47fd3)

"People also search for..." section

![image](https://github.com/catppuccin/userstyles/assets/97406176/d9faa02d-8846-4fe4-bcf6-f9723b7d9bbc)

videos: description section

![image](https://github.com/catppuccin/userstyles/assets/97406176/10bf722b-ab81-46d1-bdd6-0ba503129660)

### What browser(s) are you seeing the problem on?

Firefox 126.0.1

**Comment by uncenter** [comment]
> background should be set to none to remove the default linear gradient
or just theme it...??
