### ISSUE TITLE
Support Mastodon "System" theme

### ISSUE THREAD

**Issue by cyrneko** [catppuccin/userstyles#966]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:mastodon

### Describe your problem.

With recent changes to Mastodon they have introduced an option to automatically change dark/light themes. Sadly, this is not backwards-compatible with the "Mastodon Light" and "Mastodon Dark" themes which's variables where used before.

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/58338843/2d008991-4886-499f-a3da-7633ef1c8b77)

### What browser(s) are you seeing the problem on?

Any, but I use LibreWolf 126.0

### Any additional comments?

N/A

**Comment by uncenter** [comment]
As illustrated in your screenshot, this doesn't seem like a "recent change to Mastodon" and more something your Glitch instance added that isn't universal across all Mastodon sites. For example, I'm not seeing this on fosstodon.org.

**Comment by cyrneko** [comment]
> As illustrated in your screenshot, this doesn't seem like a "recent change to Mastodon" and more something your Glitch instance added that isn't universal across all Mastodon sites. For example, I'm not seeing this on fosstodon.org.

No, this is an official Mastodon change. My instance recently merged upstream when I made the issue.

https://github.com/mastodon/mastodon/commit/02ea16150647ac3baf0bb8a89203ccc7200b4a2f

**Comment by uncenter** [comment]
Sure, but I still can't reproduce so I can't make a fix.

**Comment by isabelroses** [comment]
I can write a patch for this based of the source shared, cannot test it though!

**Comment by cyrneko** [comment]
> I can write a patch for this based of the source shared, cannot test it though!

![image](https://github.com/user-attachments/assets/67257ca4-77f7-4c8d-8f98-fe679ef66926)

Seems to work!
