### ISSUE TITLE
Support Inoreader's new UI!

### ISSUE THREAD

**Issue by eeelbrens** [catppuccin/userstyles#979]
### Is there an existing issue outlining your problem?

- [X] I am using the latest version of the provided userstyle.
- [X] I have searched the existing issues and they do not solve my problem.

### What userstyles are you seeing the problem on?

lbl:inoreader

### Describe your problem.

The new Inoreader UI rolled out to Beta users, and will be enforced to all users on July 1st.
[source](https://mastodon.social/@Inoreader/112598076579595851)

### Attach screenshots.

![image](https://github.com/catppuccin/userstyles/assets/130598002/898ebe4f-8f1f-440b-9a92-c0f95edcb006)

### What browser(s) are you seeing the problem on?

Chromium v125.0.6422.112

**Comment by uncenter** [comment]
@Thomas-Philippot would you be able to take a look at this? I have you listed as maintainer here and this new UI is supposedly rolling out tomorrow!

**Comment by Thomas-Philippot** [comment]
> @Thomas-Philippot would you be able to take a look at this? I have you listed as maintainer here and this new UI is supposedly rolling out tomorrow!

I will not be able to pull a new version for tomorrow but definitely in the next couple of days

**Comment by uncenter** [comment]
Great thank you!
